import {newCase,isKaih} from './kaih-case.mjs';
import {caseInteriorControls} from './kaih-ui.mjs';
import {t,errorText,onLanguageChange} from './i18n.mjs';
import {ot} from './online-i18n.mjs';
import {CASE_PROFILE,JCARD_PROFILE,CASE_PROFILES,originalSetDimensions} from './geometry.mjs';
import {emptyTrackList,manualRow,capacity,formatDuration,parseDuration,editRow,moveRow,renumber,importTracks,TRACK_LIMIT,printRows} from './tracks.mjs';
export function initCaseUI({getSets,getSettings,getTarget,changed,exportCase,showCase,online}){
 const root=document.createElement('section');root.id='case-editor';root.className='online-lookup';document.querySelector('#editor-form').append(root);
 const undo=new Map();let preview=null,epoch=0,busy=false,message=null;
 const node=(tag,props={},children=[])=>{const el=document.createElement(tag);Object.assign(el,props);el.append(...children);return el;};
 const button=(key,fn,id)=>{const b=node('button',{type:'button',textContent:t(key),className:'button secondary'});if(id)b.id=id;b.onclick=fn;return b;};
 const label=(key,control)=>node('label',{},[node('span',{textContent:t(key)}),control]);
 const snapshot=()=>undo.set(getTarget().id,structuredClone(getTarget().trackList));
 const mutate=fn=>{snapshot();fn(getTarget().trackList);changed();display();};
 function invalidate(){epoch++;preview=null;busy=false;message=null;display();}
 function resetProject(){undo.clear();invalidate();}
 function display(){const exportDisabled=root.querySelector('#export-case')?.disabled??true;const set=getTarget(),settings=getSettings(),list=set.trackList||(set.trackList=emptyTrackList()),c=capacity(list,set.case?.profile);root.replaceChildren(node('h2',{textContent:t('caseTracks')}));
 const enable=node('input',{type:'checkbox',checked:!!set.case,id:'case-enabled'});enable.onchange=()=>{if(enable.checked)set.case=newCase(CASE_PROFILE.id,getSets().indexOf(set));else delete set.case;changed();display();};root.append(label('caseEnable',enable));
 const profile=CASE_PROFILES[set.case?.profile]||CASE_PROFILE;
 const top=node('div',{className:'field-row'},[button('caseLabel',showCase,'case-preview-button'),button('caseLabel',exportCase,'export-case')]);root.append(top);root.querySelector('#export-case').textContent=t('caseExport',{variant:profile.h===64?'J-Card':'CASE LABEL',width:Math.round(profile.w*300/25.4),height:Math.round(profile.h*300/25.4)});root.querySelector('#export-case').disabled=!set.case||busy||exportDisabled;
 const mode=node('select',{id:'sheet-preset'});for(const [value,key] of Object.entries({'legacy-four':'sheetNoCaseFour','case-set':'sheetCaseSingle'}))mode.append(node('option',{value,textContent:t(key)}));mode.value=settings.sheetPreset;mode.onchange=()=>{settings.sheetPreset=mode.value;settings.setCount=4;delete settings.labelAssignments;settings.sheetSetId??=getSets()[0].id;if(mode.value==='case-set'){const selected=getSets().find(s=>s.id===settings.sheetSetId);selected.case??=newCase(CASE_PROFILE.id,getSets().indexOf(selected));}changed();display();};root.append(label('sheetMode',mode),node('p',{className:'hint',textContent:t('sheetRetention')}));
 const variantControl=(target,id)=>{const select=node('select',{id});for(const [value,key] of [[CASE_PROFILE.id,'caseVariantCase'],[JCARD_PROFILE.id,'caseVariantJCard']])select.append(node('option',{value,textContent:t(key)}));select.value=target.case?.profile||CASE_PROFILE.id;select.onchange=()=>{target.case={...(target.case||newCase()),profile:select.value};changed();display();};return label('caseVariant',select);};
 if(settings.sheetPreset==='case-set'){
 const select=node('select',{id:'sheet-set'});getSets().forEach((s,i)=>select.append(node('option',{value:s.id,textContent:'ABCD'[i]+' · '+s.album})));select.value=settings.sheetSetId;select.onchange=()=>{settings.sheetSetId=select.value;delete settings.labelAssignments;const target=getSets().find(s=>s.id===select.value);target.case??=newCase(CASE_PROFILE.id,getSets().indexOf(target));changed();display();};root.append(label('sheetSet',select));
 const selected=getSets().find(s=>s.id===settings.sheetSetId);if(selected){root.append(variantControl(selected,'sheet-case-variant'),node('p',{id:'sheet-single-summary',textContent:t('sheetSingleSummary',{variant:selected.case?.profile===JCARD_PROFILE.id?'J-Card':'CASE LABEL'})}));let compatible=false;try{compatible=originalSetDimensions(selected);}catch{}if(!compatible)root.append(node('p',{role:'alert',className:'warning',textContent:t('sheetDimensionsIncompatible')}),button('sheetRestoreOriginal',()=>{Object.assign(selected,{profile:'original',w:38,h:54,sw:58,sh:3.5});changed();display();},'sheet-restore-original'));}
 }
 if(set.case&&(settings.sheetPreset!=='case-set'||settings.sheetSetId!==set.id))root.append(variantControl(set,'case-variant'));
 if(set.case)root.append(caseInteriorControls(set,{changed,message:value=>{message=value;display();}}));
 const migration=settings.layoutMigration;if(migration&&!migration.reviewed){root.append(node('p',{id:'layout-migration-notice',role:'alert',className:'warning',textContent:t('layoutMigrationNotice',{old:migration.beforeCount,new:migration.afterCount})}));if(migration.removedCount)root.append(node('p',{textContent:t('layoutMigrationRemoved',{count:migration.removedCount})}));if(migration.includesCD)root.append(node('p',{textContent:t('layoutMigrationCD')}));if(migration.changedSet)root.append(node('p',{textContent:t('layoutMigrationSameSet')}));root.append(button('layoutMigrationReview',()=>{migration.reviewed=true;changed();display();},'layout-migration-review'));}
 const cap=node('select',{id:'track-capacity'});[74,80].forEach(n=>cap.append(node('option',{value:String(n),textContent:n+' '+t('caseMinutes')})));cap.value=list.capacityMinutes;cap.onchange=()=>mutate(l=>l.capacityMinutes=Number(cap.value));const times=[['gapMs','caseGap'],['reserveMs','caseReserve']].map(([key,text])=>{const input=node('input',{type:'number',min:'0',max:'86400000',step:'1',value:list[key],id:'track-'+key});input.onchange=()=>{const value=Number(input.value);if(!Number.isInteger(value)||value<0||value>86400000){message=()=>t('caseInvalid');display();return;}mutate(l=>l[key]=value);};return label(text,input);});root.append(node('div',{className:'field-row'},[label('caseCapacity',cap),...times]));
 root.append(node('p',{id:'track-summary',textContent:t('caseSummary',{count:c.selected,total:formatDuration(c.knownMs),remaining:(c.remainingMs<0?'-':'')+formatDuration(Math.abs(c.remainingMs))})}));if(c.unknown)root.append(node('p',{className:'warning',textContent:t('caseUnknown',{count:c.unknown})}));if(c.overflowMs)root.append(node('p',{className:'warning',textContent:t('caseOverflow',{duration:formatDuration(c.overflowMs)+' ('+c.overflowMs+' '+t('caseMilliseconds')+')'})}));if(c.rowOverflow&&!isKaih(set))root.append(node('p',{className:'warning',textContent:t('caseRowOverflow',{count:c.rowOverflow,limit:printRows(set.case?.profile)})}));if(!isKaih(set))root.append(node('p',{className:'hint',textContent:t('caseTruncation',{width:profile.h===64?46:49})}));
 const tools=node('div',{className:'track-tools'},[button('caseAdd',()=>{if(list.rows.length>=TRACK_LIMIT){message=()=>t('caseInvalid');display();return;}mutate(l=>l.rows.push(manualRow(l.rows.length+1)));},'track-add'),button('caseRenumber',()=>mutate(renumber),'track-renumber'),button('caseReset',()=>{const previous=undo.get(set.id);if(previous){const current=structuredClone(list);set.trackList=previous;undo.set(set.id,current);changed();display();}},'track-undo'),button('caseSync',sync,'track-sync')]);tools.querySelector('#track-undo').disabled=!undo.has(set.id);tools.querySelector('#track-sync').disabled=busy;root.append(tools);
 const rows=node('ol',{id:'track-rows',className:'track-rows'});list.rows.forEach((row,i)=>{const li=node('li',{className:'track-row'});li.dataset.rowId=row.id;for(const [key,title,type] of [['included','caseIncluded','checkbox'],['no','caseNo','text'],['title','caseTitle','text'],['durationMs','caseDurationLabel','text']]){const input=node('input',{type});input.dataset.trackField=key;if(type==='checkbox')input.checked=row[key];else input.value=key==='durationMs'?row.durationMs===null?'':formatDuration(row.durationMs)+(row.durationMs%1000?'.'+String(row.durationMs%1000).padStart(3,'0'):''):row[key];input.maxLength=key==='title'?2000:key==='no'?20:20;input.onchange=()=>{try{const value=key==='included'?input.checked:key==='durationMs'?parseDuration(input.value):input.value;mutate(()=>editRow(row,key,value));}catch(e){message=e;display();}};li.append(label(title,input));}
 if(row.provenance)li.append(node('span',{className:'hint',textContent:t('caseDisc',{no:row.provenance.discNumber})+' · '+row.provenance.trackNumber}));
 const up=button('caseUp',()=>mutate(l=>moveRow(l,row.id,-1)));up.disabled=i===0;const down=button('caseDown',()=>mutate(l=>moveRow(l,row.id,1)));down.disabled=i===list.rows.length-1;li.append(node('div',{className:'track-tools'},[up,down,button('caseDelete',()=>mutate(l=>l.rows.splice(i,1)))]));rows.append(li);});root.append(rows);
 if(message)root.append(node('p',{role:'alert',textContent:typeof message==='function'?message():errorText(message)}));
 if(preview?.target===set&&preview.metadata===set.lookup){const data=preview.data,s=data.source;root.append(node('h3',{textContent:t('caseImportPreview')}),node('p',{textContent:sourceText(s,data.rows)}));if(!data.complete)root.append(node('p',{className:'warning',textContent:t('casePartial')}));root.append(node('ol',{},data.rows.map(r=>node('li',{textContent:t('caseDisc',{no:r.provenance.discNumber})+' · '+r.no+' · '+r.title+' · '+formatDuration(r.durationMs)}))));for(const mode of ['replace','merge'])root.append(button(mode==='replace'?'caseReplace':'caseMerge',()=>{if(preview?.target!==getTarget()||preview.metadata!==getTarget().lookup||!globalThis.confirm(t('caseConfirm',{mode:t(mode==='replace'?'caseReplace':'caseMerge')})))return;try{snapshot();set.trackList=importTracks(set.trackList,data,mode);preview=null;changed();display();}catch(e){message=e;display();}}));root.append(button('caseCancel',()=>{preview=null;display();}));}
 else if(list.source)root.append(node('p',{textContent:sourceText(list.source,list.rows)}));
 }
 function sourceText(s,rows){return t('caseSource',{source:s.source,id:s.collectionId,country:s.country,expected:s.expectedTrackCount??'—',returned:s.returnedCount,discs:[...new Set(rows.filter(r=>r.provenance).map(r=>r.provenance.discNumber))].join(', ')||'—'});}
 async function sync(){const target=getTarget(),metadata=target.lookup;if(!online.lookup.enabled||metadata?.source!=='itunes'){message=()=>t('caseSyncRequired');display();return;}const token=++epoch;busy=true;preview=null;message=null;display();try{const data=await online.lookup.tracks(metadata,{refresh:true});if(token!==epoch||getTarget()!==target||target.lookup!==metadata||!online.lookup.enabled)return;preview={target,metadata,data};}catch(e){if(token===epoch)message=()=>t('caseSyncFailed',{reason:ot(e.key||'invalid')});}finally{if(token===epoch){busy=false;display();}}}
 document.querySelectorAll('[data-set]').forEach(b=>b.addEventListener('click',invalidate));document.getElementById('load-project').addEventListener('change',invalidate);document.getElementById('online-enabled').addEventListener('change',invalidate);onLanguageChange(display);display();return {display,invalidate,resetProject};
}
