const rows={
 en:['Cover layout','Legacy (preserve saved appearance)','Coordinated layout','Old projects stay in legacy mode. Save a copy before selecting the new layout; switching back is reversible and preserves all text and images.','Image fitting','Whole image · background padding','Centered crop · fill','More than 13 track rows: export blocked. No tracks were deleted.','Coordinated background: artwork and text panels use separate protected regions; contain keeps the whole image, while cover deliberately crops.'],
 'zh-Hans':['封面排版','旧版（保留保存时外观）','协调排版','旧项目保留旧版。选择新排版前请保存副本；可切回旧版，文字和图片不会丢失。','图片适配','完整图片 · 背景色补边','居中裁切 · 铺满','曲目超过13行：已阻止导出，未删除任何曲目。','协调背景：图片与文字面板分区保护；完整图片保留全图，居中裁切为主动裁切。'],
 'zh-Hant':['封面排版','舊版（保留儲存時外觀）','協調排版','舊專案保留舊版。選擇新排版前請儲存副本；可切回舊版，文字和圖片不會遺失。','圖片適配','完整圖片 · 背景色補邊','置中裁切 · 鋪滿','曲目超過13行：已阻止匯出，未刪除任何曲目。','協調背景：圖片與文字面板分區保護；完整圖片保留全圖，置中裁切為主動裁切。'],
 es:['Diseño de portada','Clásico (conservar aspecto guardado)','Diseño coordinado','Los proyectos antiguos conservan su diseño. Guarda una copia antes de cambiar; puedes volver sin perder texto ni imágenes.','Ajuste de imagen','Imagen completa · fondo de relleno','Recorte centrado · llenar','Más de 13 pistas: exportación bloqueada. No se borraron pistas.','Fondo coordinado: imagen y paneles de texto separados; la imagen completa se conserva, o se recorta al elegir llenar.'],
 fr:['Disposition de la pochette','Ancienne (aspect enregistré)','Disposition coordonnée','Les anciens projets gardent leur aspect. Enregistrez une copie avant de changer ; le retour conserve textes et images.','Ajustement de l’image','Image entière · marges de fond','Recadrage centré · remplir','Plus de 13 pistes : export bloqué. Aucune piste supprimée.','Fond coordonné : image et panneaux de texte séparés ; l’image entière est conservée, sauf recadrage choisi.'],
 ja:['カバーの配置','従来（保存時の外観を維持）','調和レイアウト','旧プロジェクトは従来の配置を維持します。変更前にコピーを保存してください。元に戻せ、文字と画像は失われません。','画像の配置方法','画像全体 · 背景色で余白補完','中央トリミング · 全面充填','曲目が13行を超えるため出力を停止しました。曲目は削除されていません。','調和背景：画像と文字パネルを別領域で保護します。画像全体を保持し、中央トリミングは選択時のみ行います。']
};
const keys=['coverLayout','coverLegacy','coverCoordinated','coverMigration','coverFitMode','coverContain','coverCrop','unsafeRows','coverDecorative'];
export function extendCoverMessages(messages){for(const [lang,values] of Object.entries(rows))Object.assign(messages[lang],Object.fromEntries(keys.map((k,i)=>[k,values[i]])));}
