import {Lookup,LookupError,Stages,Debouncer,meaningful,ConfirmedMappings,metadataRecord} from './online.mjs';
import {ot} from './online-i18n.mjs';
import {onLanguageChange} from './i18n.mjs';
export function initOnline({getTarget,applyMetadata,applyCover,getResolution}){
 const root=document.createElement('section');root.id='online-lookup';root.className='online-lookup';root.innerHTML=`<label class="online-toggle"><input id="online-enabled" type="checkbox"><span data-online="toggle"></span></label><p class="hint" data-online="privacy"></p><div id="online-controls" hidden><div class="field-row"><label><span data-online="provider"></span><select id="online-source"><option value="musicbrainz">MusicBrainz</option><option value="itunes" selected>iTunes · Apple</option></select></label><label><span data-online="store"></span><select id="online-store"><option value="US">US</option><option value="TW">TW</option><option value="JP">JP</option><option value="HK">HK</option><option value="CN">CN</option><option value="GB">GB</option><option value="FR">FR</option><option value="ES">ES</option></select></label></div><label><span data-online="artist"></span><input id="online-artist" maxlength="200" autocomplete="off"></label><label><span data-online="album"></span><input id="online-album" maxlength="200" autocomplete="off" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="online-results"></label><button id="online-search" type="button" class="button secondary" data-online="search"></button><p class="hint" id="online-store-hint" data-online="storeHint" hidden></p><p class="hint" data-online="edition"></p><ul id="online-results" role="listbox"></ul><p id="online-message" role="status" aria-live="polite"></p><ol id="online-stages" aria-live="polite"></ol><p id="online-provenance" class="hint"></p><button id="online-cover" type="button" class="button secondary" hidden data-online="importCover"></button><p id="online-resolution" class="hint" role="status"></p><p class="hint" data-online="manual"></p></div>`;
 document.querySelector('.fields').after(root);const $=id=>root.querySelector('#online-'+id),lookup=new Lookup(),mappings=new ConfirmedMappings();let generation=0,coverEpoch=0,candidates=[],selected=null,artistId='',artistName='',message='',resolution=null,matchEpoch=0;
 const stageLabels={search:'searchStage',selected:'selectedStage',match:'matchStage',cover:'coverStage',import:'importStage'};
 function display(){$('store-hint').hidden=!($('source').value==='itunes'&&$('store').value==='CN');if(resolution&&getResolution){try{resolution=getResolution();}catch{resolution=null;}}root.querySelectorAll('[data-online]').forEach(el=>el.textContent=ot(el.dataset.online));$('artist').setAttribute('aria-label',ot('artist'));$('album').setAttribute('aria-label',ot('album'));$('message').textContent=message?ot(message):'';$('provenance').textContent=selected?ot('source',{source:selected.source,id:selected.id})+(selected.coverMbid?' · MusicBrainz '+selected.coverMbid:''):'';$('resolution').textContent=resolution?ot(resolution.low?'low':'resolution',resolution):'';$('stages').replaceChildren(...Object.entries(stages.states).map(([key,state])=>{const li=document.createElement('li');li.dataset.stage=key;li.dataset.status=state.status;const text=document.createElement('span');text.textContent=ot(stageLabels[key])+' — '+ot(state.status==='error'?'error':state.status)+(state.error?' · '+ot(state.error):'')+(state.http?' ['+state.http+']':'');li.append(text);if(state.retry){const button=document.createElement('button');button.type='button';button.className='text-button';button.dataset.retry=key;button.textContent=ot('retry');button.onclick=()=>{void state.retry();};li.append(button);}else if(state.status==='error'&&state.tries>=3){li.append(document.createTextNode(' · '+ot('manual')));}return li;}));renderCandidates();}
 const stages=new Stages(display);
 function renderCandidates(){const list=$('results');list.replaceChildren(...candidates.map((candidate,i)=>{const li=document.createElement('li');li.setAttribute('role','option');li.id='online-option-'+i;li.setAttribute('aria-selected','false');const button=document.createElement('button');button.type='button';button.dataset.candidate=String(i);button.textContent=ot('choose')+' · '+(candidate.kind==='artist'?candidate.artist:[candidate.album,candidate.artist,candidate.year||'—'].join(' · '))+' · '+candidate.source+(candidate.note?' · '+candidate.note:'')+(candidate.source==='musicbrainz'?' · MBID '+candidate.id.slice(0,8):'');button.onclick=()=>choose(candidate);li.append(button);return li;}));$('album').setAttribute('aria-expanded',String(candidates.length>0));}
 function reset(){generation++;lookup.cancel();debounce.cancel();stages.reset();selected=null;candidates=[];message='';resolution=null;artistId='';artistName='';$('cover').hidden=true;display();}
 function valid(token,target){return lookup.enabled&&token===generation&&getTarget()===target;}
 function task(name,fn){const token=generation,target=getTarget();return stages.run(name,async()=>{if(!valid(token,target))throw new LookupError('cancelled');return fn(()=>valid(token,target));});}
 async function search(){if(!lookup.enabled||debounce.composing||!meaningful($('album').value,$('artist').value))return;generation++;lookup.cancel();stages.reset();candidates=[];selected=null;resolution=null;$('cover').hidden=true;message='';display();await task('search',async ok=>{let result;const title=$('album').value.trim(),artist=$('artist').value.trim();if($('source').value==='itunes')result=await lookup.itunes(title,artist,$('store').value);else if(artist&&(!artistId||artist!==artistName)){result=await lookup.artists(artist);}else if(title)result=await lookup.groups(title,artist,artistId);else result=[];if(!ok())throw new LookupError('cancelled');candidates=result;message=result.length?(result[0].kind==='artist'?'artistChoice':''):($('source').value==='itunes'&&$('store').value==='CN'?'cnEmpty':'empty');display();});}
 async function choose(candidate){if(!lookup.enabled)return;debounce.cancel();if(candidate.kind==='match'){const id=candidate.id;if(selected){selected.coverMbid=id;mappings.set(selected,id);}candidates=[];message='';stages.set('match','done');display();void fetchCover(id,matchEpoch);return;}if(candidate.kind==='artist'){artistId=candidate.id;artistName=candidate.artist;$('artist').value=artistName;await search();return;}if(!globalThis.confirm(ot('overwrite')))return;generation++;lookup.cancel();selected=metadataRecord(candidate);candidates=[];resolution=null;stages.reset();applyMetadata(selected);stages.set('selected','done');$('cover').hidden=false;display();}
 async function fetchCover(id,epoch){const metadata=selected;if(selected)selected.coverMbid=id;display();await task('cover',async ok=>{let blob;try{blob=await lookup.cover(id);}catch(e){if(metadata?.source==='itunes'&&e.key!=='cancelled'){mappings.remove(metadata);if(selected===metadata)delete selected.coverMbid;}throw e;}if(!ok()||epoch!==coverEpoch)throw new LookupError('cancelled');const imported=await task('import',async stillOK=>{const decoded=await applyCover(blob,()=>stillOK()&&epoch===coverEpoch,id);if(!stillOK()||epoch!==coverEpoch)throw new LookupError('cancelled');resolution=decoded;display();return true;});if(metadata?.source==='itunes'&&selected===metadata){if(imported){metadata.coverMbid=id;mappings.set(metadata,id);}else{mappings.remove(metadata);delete metadata.coverMbid;}}});}
 async function matchAndCover(){const metadata={...selected},epoch=coverEpoch;const cached=mappings.get(metadata);if(cached){stages.set('match','done');message='cachedMatch';display();await fetchCover(cached,epoch);return;}const result=await task('match',async ok=>{const result=await lookup.crossMatch(metadata,ok);if(!ok())throw new LookupError('cancelled');if(!result.candidates.length)throw new LookupError('noMatch');candidates=result.candidates.map(v=>({...v,kind:'match'}));message=result.fallback?(result.truncated?'fallbackMore':'fallbackChoice'):'matchChoice';matchEpoch=epoch;return {...result,awaitingChoice:true};});}
 $('enabled').onchange=()=>{lookup.enable($('enabled').checked);$('controls').hidden=!lookup.enabled;reset();};
 const debounce=new Debouncer(search);for(const id of ['artist','album']){const input=$(id);input.addEventListener('compositionstart',()=>debounce.composition(true));input.addEventListener('compositionend',()=>debounce.composition(false));input.addEventListener('input',()=>{if(id==='artist'){artistId='';artistName='';}generation++;lookup.cancel();debounce.input();});}
 $('search').onclick=()=>{debounce.cancel();void search();};for(const id of ['source','store'])$(id).onchange=()=>{reset();};
 $('cover').onclick=()=>{if(!selected||!lookup.enabled||!globalThis.confirm(ot('rights')))return;generation++;lookup.cancel();coverEpoch++;resolution=null;message='';for(const key of ['match','cover','import'])delete stages.states[key];display();if(selected.source==='musicbrainz')void fetchCover(selected.id,coverEpoch);else void matchAndCover();};
 $('album').addEventListener('keydown',e=>{if(debounce.composing||e.isComposing)return;if(e.key==='ArrowDown'&&candidates.length){e.preventDefault();$('results').querySelector('button')?.focus();}if(e.key==='Escape'){candidates=[];display();}});
 $('results').addEventListener('keydown',e=>{const buttons=[...$('results').querySelectorAll('button')],i=buttons.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();buttons[(i+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length]?.focus();}if(e.key==='Escape'){candidates=[];display();$('album').focus();}});
 // Explicit local actions take precedence over any asynchronous cover import.
 for(const id of ['art-file','clear-art','random'])document.getElementById(id).addEventListener(id==='art-file'?'change':'click',()=>{coverEpoch++;lookup.cancel();for(const key of ['match','cover','import'])delete stages.states[key];stages.version++;resolution=null;display();},true);
 document.querySelectorAll('[data-set]').forEach(el=>el.addEventListener('click',reset));document.getElementById('load-project').addEventListener('change',reset,true);for(const id of ['profile','front-w','front-h','hide-header','hi-md','export-mode'])document.getElementById(id).addEventListener('input',display);document.getElementById('export-mode').addEventListener('change',display);onLanguageChange(display);display();
 return {lookup,stages,reset};
}
