import {getLanguage} from './i18n.mjs';
const keys=['toggle','privacy','provider','store','artist','album','search','choose','edition','importCover','rights','overwrite','manual','low','resolution','searchStage','selectedStage','matchStage','coverStage','importStage','waiting','running','done','error','retry','empty','network','busy','rate','missing','invalid','timeout','offline','cancelled','source','artistChoice'];
export const onlineMessages={
 en:['Online album lookup (optional)','Off by default. Live suggestions send typed album/artist text, IP and timing to your selected provider (MusicBrainz or Apple). Cover import also contacts MusicBrainz and Internet Archive. No local files are uploaded. Turning off cancels pending work, not requests already sent.','Suggestion source','Apple storefront (not UI language)','Search artist','Search album','Search','Select','Check artist, year and edition. Remasters, tributes and representative covers may differ from your disc.','Import CAA cover…','Import this cover from Cover Art Archive / Internet Archive? Cover rights are not transferred. Only import artwork you have permission to reproduce; printing or sharing a project may require rights-holder permission. Each import needs confirmation.','Apply selected metadata, replacing the current album, artist and year? All fields stay editable.','Enter metadata manually or upload your own cover. Printing stays available.','Low resolution: {w} × {h}px; below 600px or the current 300 DPI artwork area. Printing is not blocked.','Decoded cover: {w} × {h}px. Representative album cover; edition may differ.','Searching','Candidate selected · metadata applied','MusicBrainz cross-match','CAA cover fetch','Cover decode / import','Waiting','In progress…','Done','Failed','Retry this step','No matches. Try a native-script name or select another source.','Network / CORS failure. Check connectivity; retry or enter manually.','Service busy (503). Retry later.','Rate limited. Wait before retrying.','Cover / record unavailable (404).','Invalid or oversized response / image.','Request timed out. Retry or use manual entry.','Online mode is off.','Cancelled','Metadata source: {source} · {id}','Select the intended artist first; aliases and same-name artists can differ.'],
 'zh-Hans':['在线专辑查询（可选）','默认关闭。实时建议会将输入的专辑/歌手、IP及请求时间发送给所选服务（MusicBrainz或Apple）。导入封面还会访问MusicBrainz和Internet Archive。不上传本地文件。关闭会取消待处理任务，但无法撤回已发送请求。','建议来源','Apple商店地区（独立于界面语言）','搜索歌手','搜索专辑','搜索','选择','请核对歌手、年份和版本。重制、致敬专辑及代表封面可能不同于您的唱片。','导入CAA封面…','从Cover Art Archive / Internet Archive导入此封面？封面版权不会转移。请仅导入您有权复制的图片；打印或分享项目可能需要权利人许可。每次导入都需确认。','应用所选资料并替换当前专辑、歌手和年份？所有字段仍可编辑。','可手动填写资料或上传自己的封面。打印不受影响。','分辨率偏低：{w} × {h}px；低于600px或当前300 DPI图片区域要求。不会阻止打印。','封面实际尺寸：{w} × {h}px。代表性专辑封面，版本可能不同。','正在搜索','已选择候选 · 资料已填入','MusicBrainz交叉匹配','CAA封面获取','封面解码 / 导入','等待','进行中…','完成','失败','重试此步骤','无匹配。请尝试原文名称或选择其他来源。','网络 / CORS失败。请检查网络、重试或手动填写。','服务繁忙（503）。请稍后重试。','请求受限。请等待后重试。','封面 / 记录不可用（404）。','响应 / 图片无效或过大。','请求超时。可重试或手动输入。','在线模式已关闭。','已取消','资料来源：{source} · {id}','请先选择正确歌手；别名和同名歌手可能不同。'],
 'zh-Hant':['線上專輯查詢（可選）','預設關閉。即時建議會將輸入的專輯/歌手、IP及請求時間傳送給所選服務（MusicBrainz或Apple）。匯入封面還會存取MusicBrainz與Internet Archive。不上傳本機檔案。關閉會取消待處理工作，但無法撤回已傳送請求。','建議來源','Apple商店地區（獨立於介面語言）','搜尋歌手','搜尋專輯','搜尋','選擇','請核對歌手、年份及版本。重製、致敬專輯與代表封面可能不同於您的唱片。','匯入CAA封面…','從Cover Art Archive / Internet Archive匯入此封面？封面版權不會轉移。請僅匯入您有權複製的圖片；列印或分享專案可能需要權利人許可。每次匯入均需確認。','套用所選資料並取代目前專輯、歌手及年份？所有欄位仍可編輯。','可手動填寫資料或上傳自己的封面。列印不受影響。','解析度偏低：{w} × {h}px；低於600px或目前300 DPI圖片區域要求。不會阻止列印。','封面實際尺寸：{w} × {h}px。代表性專輯封面，版本可能不同。','正在搜尋','已選擇候選 · 資料已填入','MusicBrainz交叉比對','CAA封面取得','封面解碼 / 匯入','等待','進行中…','完成','失敗','重試此步驟','無符合項目。請嘗試原文名稱或選擇其他來源。','網路 / CORS失敗。請檢查網路、重試或手動填寫。','服務忙碌（503）。請稍後重試。','請求受限。請等待後重試。','封面 / 記錄不可用（404）。','回應 / 圖片無效或過大。','請求逾時。可重試或手動輸入。','線上模式已關閉。','已取消','資料來源：{source} · {id}','請先選擇正確歌手；別名及同名歌手可能不同。'],
 es:['Buscar álbum en línea (opcional)','Desactivado por defecto. Las sugerencias envían el álbum/artista escrito, IP y horario al proveedor elegido (MusicBrainz o Apple). Importar una portada también contacta MusicBrainz e Internet Archive. No se suben archivos locales. Desactivar cancela lo pendiente, no lo ya enviado.','Fuente de sugerencias','Tienda Apple (independiente del idioma)','Buscar artista','Buscar álbum','Buscar','Seleccionar','Compruebe artista, año y edición. Remasterizaciones, tributos y portadas representativas pueden diferir del disco.','Importar portada CAA…','¿Importar esta portada de Cover Art Archive / Internet Archive? No se transfieren derechos. Importe solo imágenes que tenga permiso de reproducir; imprimir o compartir un proyecto puede requerir permiso del titular. Cada importación requiere confirmación.','¿Aplicar los datos seleccionados y reemplazar álbum, artista y año actuales? Todos siguen siendo editables.','Introduzca los datos manualmente o suba su portada. La impresión sigue disponible.','Baja resolución: {w} × {h}px; inferior a 600px o al área actual a 300 DPI. No impide imprimir.','Portada decodificada: {w} × {h}px. Portada representativa; la edición puede diferir.','Buscando','Candidato seleccionado · datos aplicados','Coincidencia MusicBrainz','Descarga de portada CAA','Decodificar / importar portada','En espera','En curso…','Listo','Error','Reintentar este paso','Sin resultados. Pruebe el nombre original u otra fuente.','Fallo de red / CORS. Compruebe la conexión; reintente o escriba manualmente.','Servicio ocupado (503). Reintente más tarde.','Límite de solicitudes. Espere antes de reintentar.','Portada / registro no disponible (404).','Respuesta / imagen inválida o demasiado grande.','Solicitud agotada. Reintente o use entrada manual.','El modo en línea está desactivado.','Cancelado','Fuente de datos: {source} · {id}','Seleccione primero al artista correcto; los alias y homónimos pueden diferir.'],
 fr:['Recherche d’album en ligne (facultative)','Désactivée par défaut. Les suggestions transmettent album/artiste saisis, IP et horaire au fournisseur choisi (MusicBrainz ou Apple). Importer une pochette contacte aussi MusicBrainz et Internet Archive. Aucun fichier local envoyé. Désactiver annule les tâches en attente, pas les requêtes déjà envoyées.','Source des suggestions','Boutique Apple (indépendante de la langue)','Rechercher un artiste','Rechercher un album','Rechercher','Sélectionner','Vérifiez artiste, année et édition. Remasters, hommages et pochettes représentatives peuvent différer du disque.','Importer une pochette CAA…','Importer cette pochette depuis Cover Art Archive / Internet Archive ? Les droits ne sont pas transférés. Importez uniquement une image que vous pouvez reproduire ; imprimer ou partager un projet peut nécessiter l’autorisation du titulaire. Chaque importation doit être confirmée.','Appliquer les données et remplacer album, artiste et année actuels ? Tous les champs restent modifiables.','Saisissez les données ou importez votre pochette manuellement. L’impression reste disponible.','Faible résolution : {w} × {h}px ; inférieure à 600px ou à la zone actuelle à 300 DPI. L’impression n’est pas bloquée.','Pochette décodée : {w} × {h}px. Pochette représentative ; l’édition peut différer.','Recherche','Candidat sélectionné · données appliquées','Correspondance MusicBrainz','Téléchargement CAA','Décodage / importation','En attente','En cours…','Terminé','Échec','Réessayer cette étape','Aucun résultat. Essayez le nom original ou une autre source.','Échec réseau / CORS. Vérifiez la connexion ; réessayez ou saisissez manuellement.','Service occupé (503). Réessayez plus tard.','Limite de requêtes. Patientez avant de réessayer.','Pochette / entrée indisponible (404).','Réponse / image invalide ou trop volumineuse.','Délai dépassé. Réessayez ou saisissez manuellement.','Le mode en ligne est désactivé.','Annulé','Source des données : {source} · {id}','Sélectionnez d’abord le bon artiste ; alias et homonymes peuvent différer.'],
 ja:['オンラインアルバム検索（任意）','初期状態はオフです。候補検索は入力したアルバム/アーティスト、IPと時刻を選択したサービス（MusicBrainzまたはApple）へ送信します。ジャケットの取り込みではMusicBrainzとInternet Archiveにも接続します。ローカルファイルは送信しません。オフにしても送信済みのリクエストは取り消せません。','候補の取得元','Appleストア地域（表示言語とは別）','アーティスト検索','アルバム検索','検索','選択','アーティスト、年、版を確認してください。リマスター、トリビュートや代表画像はお持ちの盤と異なる場合があります。','CAAジャケットを取り込む…','Cover Art Archive / Internet Archiveから取り込みますか？著作権は移転されません。複製する権利のある画像のみ取り込んでください。印刷やプロジェクト共有には権利者の許可が必要な場合があります。取り込みごとに確認が必要です。','選択した情報で現在のアルバム、アーティスト、年を置き換えますか？すべての欄は引き続き編集できます。','情報の手入力や画像のアップロードも可能です。印刷は妨げられません。','低解像度：{w} × {h}px。600pxまたは現在の300 DPI画像領域の必要値未満です。印刷は可能です。','画像サイズ：{w} × {h}px。代表画像のため版が異なる場合があります。','検索中','候補選択済み · 情報を適用','MusicBrainz照合','CAAジャケット取得','画像デコード / 取り込み','待機','処理中…','完了','失敗','この段階を再試行','該当なし。原語の名前または別の取得元をお試しください。','ネットワーク / CORSエラー。接続確認、再試行または手入力してください。','サービス混雑（503）。後で再試行してください。','リクエスト制限。時間を置いて再試行してください。','画像 / レコードがありません（404）。','応答 / 画像が無効または大きすぎます。','タイムアウト。再試行または手入力してください。','オンラインモードはオフです。','キャンセル済み','情報の取得元：{source} · {id}','まず正しいアーティストを選択してください。同名や別名に注意してください。']
};
const errors={en:['No matching album family.','No front artwork in this archive record.','Unsupported or unsafe image URL.','Image could not be decoded locally.'],'zh-Hans':['没有匹配的专辑系列。','此档案记录没有正面封面。','图片网址不受支持或不安全。','图片无法在本地解码。'],'zh-Hant':['沒有符合的專輯系列。','此檔案記錄沒有正面封面。','圖片網址不受支援或不安全。','圖片無法在本機解碼。'],es:['No coincide ninguna familia de álbumes.','Este registro no contiene portada frontal.','URL de imagen no admitida o insegura.','No se pudo decodificar la imagen localmente.'],fr:['Aucune famille d’album correspondante.','Cette archive ne contient pas de pochette avant.','URL d’image non prise en charge ou dangereuse.','Impossible de décoder l’image localement.'],ja:['一致するアルバムがありません。','この記録には表ジャケットがありません。','画像URLが未対応または安全ではありません。','画像をローカルでデコードできません。']};
for(const [lang,values] of Object.entries(onlineMessages)){for(const key of ['busy','missing'])values[keys.indexOf(key)]=values[keys.indexOf(key)].replace(/\s*[（(](?:404|503)[）)]/g,'');values.push(...errors[lang]);}
keys.push('noMatch','noFront','unsafe','decode');
const storefrontMessages={
 en:['Apple catalogs vary by storefront. For Chinese music, try TW or HK if CN results are missing or unrelated. Changing the storefront sends a new search only when you search.','No album results in the CN storefront. Try TW or HK, a native-script name, or another source.','The service returned an HTTP error.'],
 'zh-Hans':['Apple目录因商店地区而异。中文音乐在CN缺失或结果不相关时，可尝试TW或HK。切换地区后需重新搜索，不会自动发送请求。','CN商店地区没有专辑结果。请尝试TW或HK、原文名称或其他来源。','服务返回了HTTP错误。'],
 'zh-Hant':['Apple目錄因商店地區而異。中文音樂在CN缺少或結果不相關時，可嘗試TW或HK。切換地區後需重新搜尋，不會自動傳送請求。','CN商店地區沒有專輯結果。請嘗試TW或HK、原文名稱或其他來源。','服務傳回了HTTP錯誤。'],
 es:['Los catálogos de Apple varían por tienda. Para música china, pruebe TW o HK si CN ofrece resultados ausentes o irrelevantes. Cambiar la tienda no envía una consulta hasta buscar.','Sin álbumes en la tienda CN. Pruebe TW o HK, el nombre original u otra fuente.','El servicio devolvió un error HTTP.'],
 fr:['Les catalogues Apple varient selon la boutique. Pour la musique chinoise, essayez TW ou HK si les résultats CN sont absents ou inadaptés. Changer de boutique n’envoie une requête que lors de la recherche.','Aucun album dans la boutique CN. Essayez TW ou HK, le nom original ou une autre source.','Le service a renvoyé une erreur HTTP.'],
 ja:['Appleのカタログはストア地域で異なります。中国語の音楽でCNの結果がない・一致しない場合はTWやHKをお試しください。地域変更だけでは送信せず、再検索時に送信します。','CNストアにアルバムの検索結果がありません。TWやHK、原語の名前、別の取得元をお試しください。','サービスからHTTPエラーが返されました。']
};
for(const [lang,values] of Object.entries(onlineMessages))values.push(...storefrontMessages[lang]);
keys.push('storeHint','cnEmpty','http');
export function ot(key,vars={}){const i=keys.indexOf(key),text=onlineMessages[getLanguage()]?.[i]||onlineMessages.en[i]||key;return text.replace(/\{(\w+)\}/g,(_,k)=>String(vars[k]??''));}
export const onlineKeys=keys;
