import assert from 'node:assert/strict';
import {Lookup,LookupError,RateLimiter,Stages,Debouncer,escapeLucene,groupQuery,titleQuery,rank,canonicalTitle,metadataRecord,meaningful} from '../online.mjs';
import {onlineMessages,onlineKeys} from '../online-i18n.mjs';
let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++;};
const id='b539e453-c4fe-47e3-8a07-8517eac74429';
check(escapeLucene('AC/DC +(x):"a"')==='AC\\/DC \\+\\(x\\)\\:\\"a\\"','Lucene escaping');check(groupQuery('first lov',id).includes('arid:'+id+' AND releasegroup:(first~1 AND (lov* OR lov~1)) AND primarytype:album'),'two-stage query');check(!titleQuery('宇多田 ヒカル').includes('~'),'CJK not Latin-fuzzed');check(titleQuery('21')==='"21"','numeric exact token');check(meaningful('浮躁','')&&!meaningful('a',''),'CJK threshold');check(canonicalTitle('K2HD: 淡淡幽情')==='淡淡幽情','CJK decoration');check(canonicalTitle('First Love (Remastered 2014)')==='First Love','edition suffix');check(canonicalTitle('Title (Live)')==='Title','live suffix intentionally removed for family match');
check(rank([{album:'依然范特西',artist:'周杰倫',year:'2006'},{album:'范特西',artist:'周杰倫',year:'2001'}],'范特西','周杰倫')[0].year==='2001','wrong-edition rerank');
for(const [lang,values] of Object.entries(onlineMessages)){check(values.length===onlineKeys.length,lang+' key parity');check(values.every(v=>typeof v==='string'&&v),'all translations');for(let i=0;i<values.length;i++)assert.deepEqual([...values[i].matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort(),[...onlineMessages.en[i].matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort());}
let now=0;const starts=[],storage={value:null,getItem(){return this.value;},setItem(k,v){this.value=v;}};const limiter=new RateLimiter('test',1300,{now:()=>now,wait:async ms=>{now+=ms;},storage,locks:null});await Promise.all([1,2,3].map(()=>limiter.run(()=>starts.push(now))));assert.deepEqual(starts,[0,1300,2600]);checks++;const second=new RateLimiter('test',1300,{now:()=>now,wait:async ms=>{now+=ms;},storage,locks:null});await second.run(()=>starts.push(now));check(starts[3]===3900,'shared budget across clients');limiter.defer(5000);await limiter.run(()=>starts.push(now));check(starts.at(-1)===8900,'Retry-After budget');
let n=0,time=0;const it=new RateLimiter('i',3100,{now:()=>time,wait:async ms=>time+=ms,storage:null,locks:null});const times=[];await Promise.all(Array.from({length:21},()=>it.run(()=>times.push(time))));check(times[20]>=60000,'iTunes real 20/min limiter');
let calls=0,queued;const debounce=new Debouncer(()=>calls++,{timer:fn=>{queued=fn;return 1;},clear:()=>{queued=null;}});debounce.composition(true);debounce.input();check(!queued&&calls===0,'no query during IME');debounce.composition(false);queued();check(calls===1,'query after composition');
const stages=new Stages();await stages.run('search',()=>{throw new LookupError('busy',503);});check(stages.states.search.status==='error'&&!!stages.states.search.retry,'per-stage retry');await stages.states.search.retry();await stages.states.search.retry();check(!stages.states.search.retry&&stages.states.search.tries===3,'bounded attempts manual fallback');stages.set('selected','done');await stages.run('cover',()=>{throw new LookupError('missing',404);});check(stages.states.selected.status==='done'&&stages.states.cover.status==='error','metadata independent of cover');stages.reset();let retryFails=true;await stages.run('match',()=>{if(retryFails)throw new LookupError('busy',503);return 'matched';});retryFails=false;await stages.states.match.retry();check(stages.states.match.status==='done'&&stages.states.match.http===0&&!stages.states.match.error,'successful retry clears old HTTP error');stages.reset();let release;const pending=stages.run('search',()=>new Promise(r=>release=r));stages.reset();release(1);await pending;check(!stages.states.search,'stale stage discarded');
const urls=[];const fast={run:fn=>fn(),defer:()=>{}};const fetcher=async url=>{urls.push(url);let data;if(url.includes('/artist/'))data={artists:[{id,name:'宇多田ヒカル'}]};else if(url.includes('itunes'))data={results:[{collectionType:'Album',collectionId:123,collectionName:'First Love (Remastered 2014)',artistName:'宇多田ヒカル',releaseDate:'1999-03-10',artworkUrl100:'https://evil.invalid/never.png'}]};else data={'release-groups':[{id,title:'First Love','primary-type':'Album','first-release-date':'1999-03-10','artist-credit':[{artist:{id,name:'宇多田ヒカル'}}]},{id:'bad',title:'single','primary-type':'Single'}]};return new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});};
const lookup=new Lookup({fetcher,mbLimiter:fast,itunesLimiter:fast});await assert.rejects(()=>lookup.artists('宇多田'),e=>e.key==='offline');check(urls.length===0,'offline zero egress');lookup.enable(true);check((await lookup.artists('宇多田'))[0].id===id,'artist fixture');check((await lookup.groups('First Lov','宇多田ヒカル',id))[0].year==='1999','artist constrained album filter');const candidates=await lookup.itunes('First Love','宇多田ヒカル','JP');check(!JSON.stringify(candidates).includes('artwork'),'Apple image discarded');check(metadataRecord(candidates[0]).source==='itunes','source recorded');await lookup.artists('宇多田');check(urls.length===3,'bounded memory cache');check(urls.every(u=>!u.includes('evil.invalid')),'never fetch Apple artwork');
lookup.enable(false);check(!lookup.cache.size,'disable clears cache');
const failed=new Lookup({fetcher:async()=>new Response('busy',{status:503,headers:{'Retry-After':'2'}}),mbLimiter:fast,itunesLimiter:fast});failed.enable(true);await assert.rejects(()=>failed.artists('oasis'),e=>e.key==='busy'&&e.status===503);checks++;
const cors=new Lookup({fetcher:async()=>{throw new TypeError('Failed to fetch');},mbLimiter:fast,itunesLimiter:fast});cors.enable(true);await assert.rejects(()=>cors.artists('oasis'),e=>e.key==='network');checks++;
console.log(JSON.stringify({status:'PASS',checks,scope:'fixtures, CJK, limiter, IME, state machine, six-language parity'}));

for(const title of ['Definitely Maybe (Remastered) [Deluxe]','Definitely Maybe [Deluxe (Remastered)]','Definitely Maybe (30th Anniversary Live Edition)'])check(canonicalTitle(title)==='Definitely Maybe','nested/chained suffix');
check(canonicalTitle('Song (For You)')==='Song (For You)'&&canonicalTitle('(Live)')==='(Live)','preserve legitimate content and nonempty base');
const jay=rank([{album:'范特西 (Live) - Single',artist:'周杰伦',year:'2001'},{album:'范特西',artist:'周杰伦',year:'2001'},{album:'依然范特西',artist:'周杰伦',year:'2006'}],'范特','周杰伦');check(jay[0].album==='范特西'&&jay.length===3,'studio first without discarding');
for(const original of ['http://coverartarchive.org/release/x/original.png','http://coverartarchive.org/release/x/1200.jpg']){let imageCalls=0;const l=new Lookup({fetcher:async url=>{if(url.includes('release-group'))return new Response(JSON.stringify({images:[{front:true,...(original.includes('1200')?{thumbnails:{1200:original}}:{image:original})}]}));imageCalls++;check(url===original.replace('http:','https:'),'CAA-only secure upgrade');if(imageCalls===1)throw new TypeError('failure');return new Response('png',{headers:{'Content-Type':'image/png'}});}});l.enable(true);await assert.rejects(()=>l.cover(id),e=>e.key==='network');await l.cover(id);check(imageCalls===2,'retry requests images');}
for(const url of ['http://archive.org/a.png','http://evil.invalid/a.png','http://coverartarchive.org.evil.invalid/a.png','http://user@coverartarchive.org/a.png','http://coverartarchive.org:8080/a.png','https://user@archive.org/a.png']){const l=new Lookup({fetcher:()=>{throw Error('must not fetch');}});l.enable(true);await assert.rejects(()=>l.request(url,{image:true}),e=>e.key==='unsafe'&&e.status===0);checks++;}
const localStages=new Stages();await localStages.run('import',()=>{throw Error('bad pixels');});check(localStages.states.import.error==='decode'&&!localStages.states.import.http,'local import decode');
for(const values of Object.values(onlineMessages))check(['missing','busy','noMatch','noFront','unsafe','decode'].every(k=>!/(404|503)/.test(values[onlineKeys.indexOf(k)])),'no invented codes');
console.log(JSON.stringify({status:'PASS',extendedChecks:checks}));

check(canonicalTitle('Title (We Live Here)')==='Title (We Live Here)','legitimate parentheses with live word retained');
check(new Lookup().mbLimiter.interval>=1200&&new Lookup().itunesLimiter.interval>=3000,'production pacing defaults');
let earlyClock=0;const earlyStarts=[],early=new RateLimiter('early',1300,{now:()=>earlyClock,wait:async ms=>{earlyClock+=Math.max(1,ms-1);},storage:null,locks:null});await Promise.all([1,2,3].map(()=>early.run(()=>earlyStarts.push(earlyClock))));check(earlyStarts.slice(1).every((n,i)=>n-earlyStarts[i]>=1200),'early timer wakes cannot violate MB minimum');
const nf=new Lookup({fetcher:async()=>new Response('{"images":[]}')});nf.enable(true);await assert.rejects(()=>nf.cover(id),e=>e.key==='noFront'&&e.status===0);checks++;
for(const [status,key] of [[404,'missing'],[503,'busy'],[400,'http']]){const l=new Lookup({mbLimiter:fast,fetcher:async()=>new Response('{}',{status})});l.enable(true);await assert.rejects(()=>l.artists('x'),e=>e.key===key&&e.status===status);checks++;}
await localStages.run('match',()=>{throw new LookupError('noMatch');});check(localStages.states.match.http===0&&localStages.states.match.error==='noMatch','local empty match has no invented404');
for(const [lang,values] of Object.entries(onlineMessages))check(values[onlineKeys.indexOf('cnEmpty')].includes('TW')&&values[onlineKeys.indexOf('cnEmpty')].includes('HK'),'CN empty help '+lang);
const storefrontURLs=[],cn=new Lookup({mbLimiter:fast,itunesLimiter:fast,fetcher:async url=>{storefrontURLs.push(new URL(url));return new Response('{"results":[]}');}});cn.enable(true);check((await cn.itunes('范特西','周杰伦','CN')).length===0,'CN200 empty is a successful empty list');check(storefrontURLs[0].searchParams.get('country')==='CN'&&storefrontURLs[0].searchParams.get('term')==='周杰伦 范特西','CN storefront and native query correctly encoded');
console.log(JSON.stringify({status:'PASS',totalChecks:checks}));
