import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname||path.dirname(new URL(import.meta.url).pathname),'..'),out=path.resolve(root,'../artifacts/autocomplete-feature');await mkdir(out,{recursive:true});
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const baseline=url.pathname.startsWith('/baseline/');let rel=decodeURIComponent(baseline?url.pathname.slice(9):url.pathname);if(rel.endsWith('/'))rel+='index.html';const base=baseline?path.resolve(process.env.AUTOCOMPLETE_BASELINE||path.resolve(root,'../artifacts/autocomplete-feature/baseline-v0.9')):root,file=path.resolve(base,'.'+rel);if(!file.startsWith(base+path.sep))throw Error();const data=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.woff2':'font/woff2','.png':'image/png'})[path.extname(file)]||'text/plain');res.end(data);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage(),errors=[],egress=[],live=[];let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++;};page.on('pageerror',e=>errors.push(e.message));
const id='b539e453-c4fe-47e3-8a07-8517eac74429',wrong='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';let searchFailures=1,matchFailures=1,coverFailures=1,delayCover=0;let coverPNG;let auditScenario="",imageAttempts=0;const requestStarts=[],auditDetails=[];
await context.route('**/*',async route=>{const url=route.request().url();if(url.startsWith(base)||url.startsWith('data:')||url.startsWith('blob:'))return route.continue();egress.push(url);requestStarts.push({url,time:Date.now()});const headers={'Access-Control-Allow-Origin':'*','Content-Type':'application/json'};if(auditScenario){
 if(url.includes('itunes.apple.com/search')){if(auditScenario==='cn-error')return route.fulfill({status:503,headers,body:'{}'});if(auditScenario==='cn')return route.fulfill({headers,body:'{"results":[]}'});const album=auditScenario==='oasis'?'Definitely Maybe (Remastered) [Deluxe]':auditScenario==='duplicates'?'吻別':'風箏';const rows=auditScenario==='rank'?[{collectionName:'范特西 (Live) - Single'},{collectionName:'范特西'},{collectionName:'依然范特西'}]:[{collectionName:album}];return route.fulfill({headers,body:JSON.stringify({results:rows.map((v,i)=>({collectionType:'Album',collectionId:100+i,artistName:auditScenario==='oasis'?'Oasis':'周杰伦',releaseDate:'2001-01-01',...v}))})});}
 if(url.includes('/artist/'))return route.fulfill({headers,body:JSON.stringify({artists:[{id,name:auditScenario==='oasis'?'Oasis':'周杰伦'}]})});
 if(url.includes('musicbrainz.org/ws/2/release-group/')){const rows=auditScenario==='no-match'?[]:auditScenario==='duplicates'?[{id,title:'吻別',disambiguation:'Taiwan original','secondary-types':[]},{id:wrong,title:'吻別',disambiguation:'Live edition','secondary-types':['Live']}]:[{id,title:auditScenario==='oasis'?'Definitely Maybe':'風箏'}];return route.fulfill({headers,body:JSON.stringify({'release-groups':rows.map(v=>({'primary-type':'Album','first-release-date':'1993-01-01','artist-credit':[{artist:{id,name:'周杰伦'}}],...v}))})});}
 if(url.includes('coverartarchive.org/release-group/')){if(auditScenario==='404')return route.fulfill({status:404,headers,body:'{}'});return route.fulfill({headers,body:JSON.stringify({images:auditScenario==='no-front'?[]:[{front:true,image:'http://coverartarchive.org/release/'+id+'/wind.png'}]})});}
 if(url.includes('coverartarchive.org/release/')){imageAttempts++;if(auditScenario==='http'&&imageAttempts===1)return route.abort();return route.fulfill({headers:{'Access-Control-Allow-Origin':'*','Content-Type':'image/png'},body:auditScenario==='decode'?Buffer.from('not a PNG'):coverPNG});}
 return route.abort();
 }
 if(url.includes('musicbrainz.org/ws/2/artist/')){if(searchFailures-->0)return route.fulfill({status:503,headers,body:'{}'});return route.fulfill({headers,body:JSON.stringify({artists:[{id,name:'宇多田ヒカル'},{id:wrong,name:'Tribute Band',disambiguation:'wrong performer'}]})});}if(url.includes('musicbrainz.org/ws/2/release-group/')){if(matchFailures-->0)return route.fulfill({status:503,headers,body:'{}'});return route.fulfill({headers,body:JSON.stringify({'release-groups':[{id,title:'First Love','primary-type':'Album','first-release-date':'1999-03-10','artist-credit':[{artist:{id,name:'宇多田ヒカル'}}]}]})});}if(url.includes('itunes.apple.com/search'))return route.fulfill({headers,body:JSON.stringify({results:[{collectionType:'Album',collectionId:1,collectionName:'First Love (Remastered 2014)',artistName:'宇多田ヒカル',releaseDate:'1999-03-10',artworkUrl100:'https://apple-art.invalid/do-not-fetch.jpg'},{collectionType:'Album',collectionId:2,collectionName:'First Love Tribute',artistName:'Tribute Band',releaseDate:'2022-01-01'}]})});if(url.includes('coverartarchive.org/')){if(delayCover)await new Promise(r=>setTimeout(r,delayCover));if(coverFailures-->0)return route.abort();return route.fulfill({headers,body:JSON.stringify({images:[{front:true,thumbnails:{1200:'https://archive.org/test-original.png'}}]})});}if(url==='https://archive.org/test-original.png'){if(delayCover)await new Promise(r=>setTimeout(r,delayCover));return route.fulfill({headers:{'Access-Control-Allow-Origin':'*','Content-Type':'image/png'},body:coverPNG});}return route.abort();});
async function settle(){await page.waitForFunction(()=>!document.getElementById('export-front').disabled,{},{timeout:60000});await page.waitForTimeout(120);}
async function stage(name,status){await page.waitForSelector(`[data-stage="${name}"][data-status="${status}"]`,{timeout:30000});}
async function snapshot(name){await page.locator('#online-lookup').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
async function pngs(p){return p.evaluate(async()=>{const {studio}=await import('./app.mjs'),{frontCanvas,spineCanvas,sheetCanvas,calibrationCanvas}=await import('./render.mjs'),{pngBlob}=await import('./png.mjs');const s=studio.getState(),canvases=[(await frontCanvas(s.sets[0],s.mode)).canvas,(await spineCanvas(s.sets[0])).canvas,(await sheetCanvas(s.sets,s.settings)).canvas,calibrationCanvas(s.settings)];return Promise.all(canvases.map(async c=>Array.from(new Uint8Array(await (await pngBlob(c)).arrayBuffer()))));});}
try{
 await page.goto(base+'/');await settle();const fresh=await pngs(page);check(egress.length===0,'default OFF zero egress');check(await page.locator('#online-source').inputValue()==='itunes','initial suggestion source defaults to iTunes');
 const baseline=await context.newPage();await baseline.goto(base+'/baseline/');await baseline.waitForFunction(()=>!document.getElementById('export-front').disabled,{},{timeout:60000});const before=await pngs(baseline);await baseline.close();
 const parity=fresh.map((bytes,i)=>{const b=Buffer.from(bytes),a=Buffer.from(before[i]);check(b.equals(a),'offline PNG byte parity '+i);return {kind:['front','spine','sheet','calibration'][i],sha256:createHash('sha256').update(b).digest('hex'),baselineSha256:createHash('sha256').update(a).digest('hex'),bytes:b.length};});await writeFile(path.join(out,'offline-parity.json'),JSON.stringify(parity,null,2));
 coverPNG=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=300;c.height=300;const x=c.getContext('2d');x.fillStyle='#164e48';x.fillRect(0,0,300,300);x.fillStyle='#ffdca3';x.fillRect(50,50,200,200);return c.toDataURL('image/png').split(',')[1];}),'base64');await writeFile(path.join(out,'original-test-cover.png'),coverPNG);
 await page.locator('#online-enabled').check();await page.locator('#online-source').selectOption('musicbrainz');await page.locator('#online-artist').dispatchEvent('compositionstart');await page.locator('#online-artist').fill('宇多田');await page.waitForTimeout(1100);check(egress.length===0,'no mid-IME query');await page.locator('#online-artist').dispatchEvent('compositionend');await stage('search','error');await snapshot('en-search-retry');await page.locator('#language').selectOption('zh-Hans');await snapshot('zh-search-retry');await page.locator('#language').selectOption('en');await page.locator('[data-retry=search]').click();await stage('search','done');check(await page.locator('[data-candidate]').count()===2,'explicit artist choice');check((await page.locator('#album').inputValue()).includes('Coastal'),'no silent fill');
 // iTunes alternative: no MB join until cover confirmation.
 await page.locator('#online-source').selectOption('itunes');await page.locator('#online-album').fill('First Lov');await stage('search','done');check(await page.locator('[data-candidate]').count()===2,'edition suggestions selectable');await snapshot('en-suggestions');await page.locator('#language').selectOption('zh-Hans');await snapshot('zh-suggestions');await page.locator('#language').selectOption('en');let accept=true;page.on('dialog',d=>accept?d.accept():d.dismiss());const mbBefore=egress.filter(u=>u.includes('musicbrainz')).length;await page.locator('[data-candidate="0"]').click();await stage('selected','done');check(await page.locator('#album').inputValue()==='First Love (Remastered 2014)','selected edition applied immediately');check(egress.filter(u=>u.includes('musicbrainz')).length===mbBefore,'no eager MB match');await page.locator('#album').fill('My editable title');await settle();check(await page.locator('#album').inputValue()==='My editable title','metadata stays editable');
 accept=false;await page.locator('#online-cover').click();check(egress.filter(u=>u.includes('musicbrainz')).length===mbBefore,'cover confirmation refusal zero egress');accept=true;await page.locator('#online-cover').click();await stage('match','error');check(await page.locator('#album').inputValue()==='My editable title','metadata survives join failure');await snapshot('en-match-retry');await page.locator('#language').selectOption('zh-Hans');await snapshot('zh-match-retry');await page.locator('[data-retry=match]').click();await stage('match','done');check(await page.locator('[data-candidate]').count()===1,'MB cross-match requires selection');await page.locator('[data-candidate="0"]').click();await stage('cover','error');await snapshot('zh-cover-retry');check(await page.locator('#export-front').isEnabled(),'cover failure never blocks printing');await page.locator('[data-retry=cover]').click();await stage('import','done');check((await page.locator('#online-resolution').textContent()).includes('300 × 300'),'decoded resolution warning');await snapshot('zh-cover-done');await page.locator('#language').selectOption('en');await snapshot('en-cover-done');
 const pngWait=page.waitForEvent('download');await page.locator('#export-front').click();await (await pngWait).saveAs(path.join(out,'sample-imported-front.png'));await settle();
 const state=await page.evaluate(async()=>{const {studio}=await import('./app.mjs');return studio.getState();});check(state.sets[0].lookup.source==='itunes'&&!JSON.stringify(state).includes('apple-art'),'metadata-only provenance');check(state.sets[0].lookup.year==='1999','no silent cross-match year replacement');
 // Manual upload wins against pending fetched cover, and replacement exports offline.
 delayCover=1300;await page.locator('#online-cover').click();await stage('match','done');await page.locator('[data-candidate="0"]').click();await stage('cover','running');await snapshot('en-cover-running');await page.locator('#art-file').setInputFiles({name:'manual-original.png',mimeType:'image/png',buffer:coverPNG});await page.waitForTimeout(1500);await settle();check(await page.evaluate(async()=>{const {studio}=await import('./app.mjs');return studio.getState().sets[0].art.name==='manual-original.png';}),'manual upload wins pending fetch');
 await page.locator('#online-enabled').uncheck();const count=egress.length;await context.setOffline(true);const download=page.waitForEvent('download');await page.locator('#export-front').click();await (await download).saveAs(path.join(out,'sample-manual-offline-front.png'));check(egress.length===count,'offline imported cover export no egress');await context.setOffline(false);
 // Pure MB artist-ID path, no auto-fill wrong performer.
 await page.locator('#online-enabled').check();await page.locator('#online-source').selectOption('musicbrainz');await page.locator('#online-artist').fill('宇多田');await page.locator('#online-album').fill('First Lov');await stage('search','done');await page.locator('[data-candidate="0"]').click();await stage('search','done');check(egress.some(u=>u.includes('release-group')&&decodeURIComponent(u).includes('arid:'+id)),'real UI two-stage artist-ID query');await page.locator('[data-candidate="0"]').click();await stage('selected','done');check(await page.locator('#year').inputValue()==='1999','MB selection fills original album year');
 for(const lang of ['zh-Hant','es','fr','ja']){await page.locator('#language').selectOption(lang);check((await page.locator('[data-online=retry]').count())===0,'locale usable '+lang);}await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile no overflow');
 check(!egress.some(u=>u.includes('apple-art')),'no Apple artwork ever requested');check(errors.length===0,'no runtime errors '+errors.join(';'));
 // Actual control regressions for all seven audit findings plus CN storefront.
 await page.setViewportSize({width:1440,height:1100});
 async function auditSearch(mode,title='風箏',store='TW'){auditScenario=mode;imageAttempts=0;await page.locator('#online-enabled').uncheck();await page.locator('#online-enabled').check();await page.locator('#online-source').selectOption('itunes');await page.locator('#online-store').selectOption(store);await page.locator('#online-artist').dispatchEvent('compositionstart');await page.locator('#online-artist').fill(mode==='oasis'?'Oasis':'周杰伦');await page.locator('#online-album').fill(title);await page.locator('#online-artist').dispatchEvent('compositionend');await page.locator('#online-search').click();await stage('search',mode==='cn-error'?'error':'done');}
 async function auditMatch(){await page.locator('[data-candidate="0"]').click();await stage('selected','done');await page.locator('#online-cover').click();await stage('match',auditScenario==='no-match'?'error':'done');}
 await auditSearch('cn','范特西','CN');check(await page.locator('[data-candidate]').count()===0,'CN empty200 no candidates');check((await page.locator('[data-stage=search]').getAttribute('data-status'))==='done','empty list distinct from error');
 for(const lang of ['en','zh-Hans','zh-Hant','es','fr','ja']){await page.locator('#language').selectOption(lang);const text=await page.locator('#online-message').innerText();check(text.includes('CN')&&text.includes('TW')&&text.includes('HK')&&!text.includes('404'),'CN empty helpful localized '+lang);check(await page.locator('#online-store-hint').isVisible(),'CN storefront catalog hint '+lang);auditDetails.push({case:'cn-empty',lang,text});}
 await page.locator('#language').selectOption('en');await auditSearch('cn-error','范特西','CN');check(!(await page.locator('#online-message').innerText()).includes('No album results'),'503 is not misreported as empty');auditScenario='cn';await page.locator('[data-retry=search]').click();await stage('search','done');
 await auditSearch('rank','范特');const jayRows=await page.locator('[data-candidate]').allTextContents();check(jayRows[0].includes('范特西')&&!jayRows[0].includes('Live')&&jayRows.length===3,'范特西 studio album outranks live single');auditDetails.push({case:'范特西-ranking',rows:jayRows});
 await auditSearch('oasis','Definitely May');await auditMatch();check(await page.locator('#album').inputValue()==='Definitely Maybe (Remastered) [Deluxe]','Oasis source edition title preserved');const oasisQuery=requestStarts.filter(v=>v.url.includes('musicbrainz.org/ws/2/release-group')).at(-1).url;check(!decodeURIComponent(oasisQuery).includes('Remastered')&&!decodeURIComponent(oasisQuery).includes('Deluxe'),'Oasis chained suffix absent from actual MB query');auditDetails.push({case:'Oasis-query',url:oasisQuery});
 await auditSearch('duplicates','吻');await auditMatch();const duplicateRows=await page.locator('[data-candidate]').allTextContents();check(duplicateRows.length===2&&duplicateRows[0]!==duplicateRows[1]&&duplicateRows.every(v=>v.includes('MBID'))&&duplicateRows[1].includes('Live edition'),'吻別 duplicates have disambiguation/types/MBID');auditDetails.push({case:'吻別-duplicates',rows:duplicateRows});
 coverPNG=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=600;c.getContext('2d').fillRect(0,0,600,600);return c.toDataURL().split(',')[1];}),'base64');
 await auditSearch('http','風箏');await auditMatch();await page.locator('[data-candidate="0"]').click();await stage('cover','error');const beforeImageRetry=egress.length;await page.locator('[data-retry=cover]').click();await stage('import','done');check(imageAttempts===2&&egress.length===beforeImageRetry+1&&egress.at(-1).startsWith('https://coverartarchive.org/release/'),'風箏 HTTP original upgraded; retry re-requests image only');check((await page.locator('#online-provenance').innerText()).includes(id),'chosen cover MBID retained');
 for(const lang of ['en','zh-Hans','zh-Hant','es','fr','ja']){await page.locator('#language').selectOption(lang);await page.locator('#profile').selectOption('custom');await page.locator('#front-w').fill('85');await page.locator('#front-h').fill('120');const large=await page.locator('#online-resolution').innerText();await page.locator('#profile').selectOption('original');const small=await page.locator('#online-resolution').innerText();check(large!==small&&large.includes('600 × 600')&&small.includes('600 × 600'),'resolution recomputes small-large-small '+lang);auditDetails.push({case:'resolution',lang,large,small});}
 await page.locator('#language').selectOption('en');await page.locator('#art-file').setInputFiles({name:'replacement.png',mimeType:'image/png',buffer:coverPNG});await settle();check((await page.locator('#online-resolution').innerText())==='','manual replacement clears resolution reassurance');
 await auditSearch('decode');await auditMatch();await page.locator('[data-candidate="0"]').click();await stage('import','error');const decodeText=await page.locator('#online-stages').innerText();check(decodeText.includes('decoded locally')&&!decodeText.includes('Network / CORS'),'bad PNG is truthful local decode failure');const decodeBefore=egress.length;await page.locator('[data-retry=import]').click();await stage('import','error');check(egress.length===decodeBefore,'decode-only retry issues no network');
 await auditSearch('no-match');await auditMatch();check(!(await page.locator('#online-stages').innerText()).includes('404')&&(await page.locator('#online-stages').innerText()).includes('No matching album'),'empty200 MB is local no-match not404');
 for(const mode of ['no-front','404']){await auditSearch(mode);await auditMatch();await page.locator('[data-candidate="0"]').click();await stage('cover','error');const text=await page.locator('#online-stages').innerText();check(mode==='404'?text.includes('[404]'):text.includes('No front artwork')&&!text.includes('404'),'truthful cover failure '+mode);auditDetails.push({case:mode,text});}
 const mbStarts=requestStarts.filter(v=>v.url.includes('musicbrainz.org')),itStarts=requestStarts.filter(v=>v.url.includes('itunes.apple.com'));const mbGaps=mbStarts.slice(1).map((v,i)=>v.time-mbStarts[i].time),itGaps=itStarts.slice(1).map((v,i)=>v.time-itStarts[i].time);check(mbGaps.every(v=>v>=1200),'native MB starts >=1200ms');check(itGaps.every(v=>v>=3000),'native iTunes starts >=3000ms');auditDetails.push({case:'native-pacing',mbGaps,itGaps});check(errors.length===0,'audit cases have no uncaught runtime errors');
 if(process.env.LIVE_AUTOCOMPLETE==='1'){
  // Network-dependent actual-browser checks, bounded three operations; no artwork.
  const c=await browser.newContext(),p=await c.newPage();await p.goto(base+'/');await p.waitForFunction(()=>!document.getElementById('export-front').disabled,{},{timeout:60000});const result=await p.evaluate(async()=>{const {Lookup}=await import('./online.mjs');const l=new Lookup();l.enable(true);const output=[];for(const [name,fn] of [['MB artist',()=>l.artists('Radiohead')],['MB group',()=>l.groups('OK Computer','Radiohead','a74b1b7f-71a5-4011-9441-d0b5e4122711')],['iTunes metadata',()=>l.itunes('Definitely Maybe','Oasis','US')]]){const start=Date.now();try{const list=await fn();output.push({name,status:list.length?'PASS':'EMPTY',count:list.length,elapsedMs:Date.now()-start,sample:list[0]});}catch(e){output.push({name,status:'NETWORK_DEPENDENT_FAILURE',error:e.key,http:e.status,elapsedMs:Date.now()-start});}}return output;});live.push(...result);await c.close();await writeFile(path.join(out,'live-api-tests.json'),JSON.stringify({networkDependent:true,operations:3,noArtwork:true,results:live},null,2));
 }
 const report={status:'PASS',checks,browser:browser.version(),runtimeErrors:errors,fixtureRequests:egress,offlineParity:parity,auditDetails,live};await writeFile(path.join(out,'autocomplete-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:'PASS',checks,live}));
}catch(e){console.error(JSON.stringify({errors,egress,ui:await page.locator('#online-lookup').innerText()}));await page.screenshot({path:path.join(out,'test-failure.png'),fullPage:true}).catch(()=>{});await writeFile(path.join(out,'test-failure.txt'),e.stack);throw e;}finally{await browser.close();server.close();}
