import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {crc32} from '../png.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.join(root,'tests/artifacts');await mkdir(out,{recursive:true});
const require=createRequire(import.meta.url);let chromium;try{({chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/xzhou/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core'));}catch{console.error('BLOCKED: set PLAYWRIGHT_MODULE to an installed playwright-core module; no browser installation is performed.');process.exit(2);}
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');let rel=decodeURIComponent(url.pathname).replace(/^\/subpath\//,'/');if(rel.endsWith('/'))rel+='index.html';const file=path.resolve(root,'.'+rel);if(!file.startsWith(root+path.sep))throw Error('outside root');const data=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.mjs':'text/javascript','.json':'application/json','.woff2':'font/woff2','.png':'image/png'})[path.extname(file)]||'text/plain');res.end(data);}catch{res.writeHead(404);res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({viewport:{width:1280,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[],requests=[];let assertions=0;const check=(v,msg)=>{assert.ok(v,msg);assertions++;};page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await context.route('**/*',route=>route.request().url().startsWith(base)||route.request().url().startsWith('blob:'+base)||route.request().url().startsWith('data:')?route.continue():route.abort());
function pngInspect(buf,w,h){check(buf.readUInt32BE(0)===0x89504e47,'PNG signature');check(buf.readUInt32BE(16)===w&&buf.readUInt32BE(20)===h,`IHDR ${w}x${h}`);let density=0;for(let at=8;at<buf.length;){const len=buf.readUInt32BE(at),type=buf.toString('ascii',at+4,at+8);check(at+12+len<=buf.length,'chunk bounds');check(buf.readUInt32BE(at+8+len)===crc32(buf.subarray(at+4,at+8+len)),`CRC ${type}`);if(type==='pHYs'){density++;check(buf.readUInt32BE(at+8)===11811&&buf.readUInt32BE(at+12)===11811&&buf[at+16]===1,'300 DPI pHYs');}at+=len+12;}check(density===1,'single density chunk');}
async function settle(){await page.waitForTimeout(180);await page.waitForFunction(()=>!document.getElementById('export-front').disabled,{},{timeout:60000});}
async function download(id,name,w,h){const wait=page.waitForEvent('download',{timeout:60000});await page.locator('#'+id).click();const d=await wait;await d.saveAs(path.join(out,name));if(w)pngInspect(await readFile(path.join(out,name)),w,h);await settle();return d;}
try{
 await page.goto(base+'/subpath/');await settle();await page.locator('#set-count').selectOption('2');await page.waitForTimeout(200);await settle();check((await page.locator('#error').isVisible())===false,'startup no error');
 const fonts=await page.evaluate(async()=>{const {studio}=await import('./app.mjs');return studio.fontDiagnostics();});check(Object.keys(fonts).length===5&&Object.values(fonts).every(f=>f.loaded),'all 5 actual FontFaces loaded');
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 await download('export-front','front-compat.png',448,637);await page.locator('#export-mode').selectOption('physical');await settle();await download('export-front','front-physical.png',449,638);await download('export-spine','spine.png',685,41);await download('export-sheet','sheet-selphy.png',1181,1748);await download('export-calibration','calibration.png',1181,1748);
 await download('export-manifest','geometry-default.json');
 await page.locator('#paper').selectOption('inch');await settle();await download('export-sheet','sheet-4x6.png',1200,1800);await page.locator('#paper').selectOption('selphy');await page.locator('#measured-x').fill('52');await page.locator('#measured-y').fill('51');await page.locator('#calibrated').check();await settle();await download('export-sheet','sheet-compensated.png',1181,1748);await download('export-manifest','geometry-compensated.json');await download('export-calibration','calibration-while-compensated.png',1181,1748);check((await readFile(path.join(out,'calibration.png'))).equals(await readFile(path.join(out,'calibration-while-compensated.png'))),'calibration stays uncorrected');
 // Actual selected-face export matrix: every CJK family × Latin face, labels with mixed glyphs.
 await page.locator('#album').fill('夜航 / Night Drive — Vol. 02');await page.locator('#artist').fill('风与海 · Mira & Satellites');await page.locator('#year').fill('2026');
 for(const cjk of ['noto-sans','noto-serif','wenkai'])for(const latin of ['atkinson','b612']){await page.locator('#cjk').selectOption(cjk);await page.locator('#latin').selectOption(latin);await settle();await download('export-front',`font-${cjk}-${latin}.png`,449,638);}
 // Pure browser renderer parity geometry and all 24 original-equivalent combinations.
 const matrix=await page.evaluate(async()=>{const {studio}=await import('./app.mjs');const {frontCanvas}=await import('./render.mjs');const state=studio.getState(),set=state.sets[0],results=[];for(const latin of ['atkinson','b612'])for(const cjk of ['noto-sans','noto-serif','wenkai'])for(const theme of ['dark','light'])for(const uppercase of [true,false])for(const hideHeader of [true,false]){const r=await frontCanvas({...set,latin,cjk,theme,uppercase,hideHeader},'compat');results.push(r.canvas.width===448&&r.canvas.height===637);}return results;});check(matrix.length===48&&matrix.every(Boolean),'48 renderer option combinations');
 const rasterChecks=await page.evaluate(async()=>{const {studio}=await import('./app.mjs');const {frontCanvas,spineCanvas,sheetCanvas}=await import('./render.mjs');const st=studio.getState(),results={opaque:true,boxes:[],fontHashes:[]};for(const kind of ['compat','physical','spine']){const r=kind==='spine'?await spineCanvas(st.sets[0]):await frontCanvas(st.sets[0],kind);const data=r.canvas.getContext('2d').getImageData(0,0,r.canvas.width,r.canvas.height).data;for(let i=3;i<data.length;i+=4)if(data[i]!==255)results.opaque=false;}const result=await sheetCanvas(st.sets.slice(0,st.settings.setCount),st.settings),ctx=result.canvas.getContext('2d');for(const set of result.manifest.sets)for(const label of set.labels){const r=label.rectPx,m=3,box=ctx.getImageData(r.x-m,r.y-m,r.width+2*m,r.height+2*m),hits=[];let minX=1e9,minY=1e9,maxX=-1,maxY=-1;for(let y=0;y<box.height;y++)for(let x=0;x<box.width;x++){const i=(y*box.width+x)*4;if(box.data[i]<245||box.data[i+1]<245||box.data[i+2]<245){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}}results.boxes.push(Math.abs(minX-m)<=1&&Math.abs(minY-m)<=1&&Math.abs(maxX-(m+r.width-1))<=1&&Math.abs(maxY-(m+r.height-1))<=1);}return results;});check(rasterChecks.opaque,'standalone PNGs fully opaque through rounded edges');check(rasterChecks.boxes.length===4&&rasterChecks.boxes.every(Boolean),'actual rendered label/cut bounds agree with manifest within one antialiased edge pixel');
 await page.locator('#set-b').click();await settle();check(await page.locator('#album').inputValue()==='深夜轨道 / Midnight Orbit','B independent');await page.locator('#album').fill('B ONLY');await page.locator('#set-a').click();await settle();check((await page.locator('#album').inputValue()).startsWith('夜航'),'A preserved');
 await page.locator('#hide-header').check();await page.locator('[name=theme][value=light]').check();await settle();await download('export-front','front-hidden-light.png',449,638);
 await page.locator('#profile').selectOption('vendor');await settle();await download('export-front','front-vendor.png',378,614);check(await page.locator('#export-mode').inputValue()==='physical','vendor cannot silently use compatibility');await page.locator('#profile').selectOption('sony');await settle();await download('export-front','front-sony.png',422,623);await page.locator('#profile').selectOption('original');
 // Local image contain fixtures created independently in this browser, then uploaded via the real control.
 const fixture=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=400;const x=c.getContext('2d');x.fillStyle='#ff0000';x.fillRect(0,0,800,400);return c.toDataURL('image/png').split(',')[1];});await writeFile(path.join(out,'landscape-input.png'),Buffer.from(fixture,'base64'));await page.locator('#art-file').setInputFiles(path.join(out,'landscape-input.png'));await settle();await download('export-front','landscape-contain.png',449,638);
 const contain=await page.evaluate(()=>{const c=document.getElementById('preview'),x=c.getContext('2d');return {top:[...x.getImageData(225,40,1,1).data],mid:[...x.getImageData(225,225,1,1).data]};});check(contain.top.slice(0,3).every(v=>v===255),'contain top white, no crop/stretch');check(contain.mid[0]===255&&contain.mid[1]===0,'contain centered red art');
 const portrait=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=800;const x=c.getContext('2d');x.fillStyle='#0000ff';x.fillRect(0,0,400,800);return c.toDataURL('image/png').split(',')[1];});await page.locator('#art-file').setInputFiles({name:'portrait.png',mimeType:'image/png',buffer:Buffer.from(portrait,'base64')});await settle();const portraitPixels=await page.evaluate(()=>{const c=document.getElementById('preview'),x=c.getContext('2d');return {side:[...x.getImageData(30,225,1,1).data],mid:[...x.getImageData(225,225,1,1).data]};});check(portraitPixels.side.slice(0,3).every(v=>v===255)&&portraitPixels.mid[2]===255&&portraitPixels.mid[0]===0,'portrait cover contain preserves ratio');await download('export-front','portrait-contain.png',449,638);
 await page.locator('#art-file').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await page.waitForFunction(()=>!document.getElementById('error').hidden);check((await page.locator('#error').textContent()).includes('解码'),'corrupt image explicitly reported');await page.locator('#redraw').click();await settle();
 await download('save-project','project.json');const saved=await readFile(path.join(out,'project.json'),'utf8');await page.locator('#album').fill('changed');await page.locator('#load-project').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(saved)});await settle();check((await page.locator('#album').inputValue()).startsWith('夜航'),'project restored');
 await page.locator('#album').fill('x'.repeat(600));await settle();check((await page.locator('#render-status').textContent()).includes('截断'),'long text truncation reported');await page.locator('#album').fill('😀');await page.waitForFunction(()=>!document.getElementById('error').hidden);check(await page.locator('#export-front').isDisabled(),'unsupported glyph blocks export');await page.locator('#album').fill('夜航 / Night Drive');await settle();
 await page.locator('[data-view=sheet]').click();await settle();await page.screenshot({path:path.join(out,'sheet-preview.png'),fullPage:true});
 await context.setOffline(true);await page.locator('#cjk').selectOption('noto-serif');await settle();await download('export-sheet','offline-sheet.png',1181,1748);await context.setOffline(false);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px no horizontal overflow');
 check(errors.length===0,'no page runtime exceptions: '+errors.join(';'));check(requests.every(u=>u.startsWith(base)||u.startsWith('blob:'+base)||u.startsWith('data:')),'no external network requests');
 // Fresh context blocks a selected font; correct failure must be visible, not fallback success.
 const failed=await browser.newContext();await failed.route('**/noto-sans.woff2',r=>r.abort());const fp=await failed.newPage();await fp.goto(base+'/');await fp.waitForFunction(()=>!document.getElementById('error').hidden,{},{timeout:60000});check(await fp.locator('#export-front').isDisabled(),'font failure blocks export');check((await fp.locator('#error').textContent()).includes('未载入'),'font failure disclosed');await failed.close();
 const delayed=await browser.newContext({deviceScaleFactor:2});await delayed.route('**/noto-sans.woff2',async r=>{await new Promise(resolve=>setTimeout(resolve,600));await r.continue();});const dp=await delayed.newPage();await dp.goto(base+'/');check(await dp.locator('#export-front').isDisabled(),'export blocked during selected font load');await dp.waitForFunction(()=>!document.getElementById('export-front').disabled,{},{timeout:60000});check(await dp.locator('#preview').evaluate(c=>c.width===448&&c.height===637),'DPR2 compatibility raster unchanged');await delayed.close();
 if(await stat(path.join(root,'dist/index.html')).catch(()=>null)){await page.goto(base+'/dist/');await settle();check(await page.locator('#error').isHidden(),'built dist startup succeeds');check(await page.evaluate(async()=>{const {studio}=await import('./app.mjs');return Object.values(studio.fontDiagnostics()).every(f=>f.loaded);}),'built dist fonts all loaded');}
 const report={status:'PASS',assertions,browser:browser.version(),fontDiagnostics:fonts,externalRequests:requests.filter(u=>!u.startsWith(base)&&!u.startsWith('data:')),runtimeErrors:errors,scope:'Local app only; original website not navigated. Real physical printing and original screenshot comparison not performed.'};await writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(path.join(out,'failure.txt'),String(e.stack));throw e;}finally{await browser.close();server.close();}
