import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createRequire} from 'node:module';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/case-label/edges');await mkdir(out,{recursive:true});const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname;if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.png':'image/png','.json':'application/json','.css':'text/css','.woff2':'font/woff2','.svg':'image/svg+xml'})[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;},eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++;};const errors=[];
async function context(route){const ctx=await browser.newContext({acceptDownloads:true});await ctx.route('**/*',route);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));return {ctx,page};}
const local=r=>r.request().url().startsWith(base+'/')||r.request().url().startsWith('blob:'+base+'/');
async function state(page){return page.evaluate(async()=> (await import('./app.mjs')).studio.getState());}
async function settle(page){await page.waitForTimeout(200);await page.waitForFunction(()=>!document.querySelector('#export-spine').disabled,null,{timeout:60000});}
try{
 // Explicit delay/failure: a selected case must never fall back to system fonts.
 let release;const gate=new Promise(r=>release=r);const delayed=await context(async r=>{if(r.request().url().endsWith('/noto-sans.woff2'))await gate;if(local(r))return r.continue();return r.abort();});await delayed.page.goto(base+'/dist/');await delayed.page.locator('#case-enabled').check();await delayed.page.locator('#case-preview-button').click();ok(await delayed.page.locator('#export-case').isDisabled(),'case waits for actual FontFace');release();await settle(delayed.page);await delayed.page.waitForFunction(()=>!document.querySelector('#export-case').disabled);ok(!await delayed.page.locator('#export-case').isDisabled(),'case ready only after font load');await delayed.ctx.close();
 const failed=await context(r=>r.request().url().endsWith('/noto-sans.woff2')?r.abort():local(r)?r.continue():r.abort());await failed.page.goto(base+'/dist/');await failed.page.locator('#case-enabled').check();await failed.page.locator('#case-preview-button').click();await failed.page.waitForFunction(()=>document.querySelector('#font-status').textContent.includes('load failed'));await failed.page.waitForFunction(()=>document.querySelector('#error').textContent.includes('not loaded'),null,{timeout:60000});ok(await failed.page.locator('#export-case').isDisabled(),'failed selected font blocks case');ok((await failed.page.locator('#error').textContent()).includes('not loaded'),'font failure visible');await failed.ctx.close();
 let holdTrack=false,lookupCount=0,releaseTrack,rate=false;const pendingTrack=new Promise(r=>releaseTrack=r);const working=await context(async r=>{const url=r.request().url();if(local(r))return r.continue();if(url.startsWith('https://itunes.apple.com/search?'))return r.fulfill({json:{results:[{collectionType:'Album',collectionId:123,collectionName:'Album',artistName:'Artist',releaseDate:'2026',trackCount:1}]}});if(url.startsWith('https://itunes.apple.com/lookup?')){lookupCount++;if(holdTrack)await pendingTrack;if(rate)return r.fulfill({status:429,headers:{'Retry-After':'1'},body:''});return r.fulfill({json:{results:[{wrapperType:'collection',collectionId:123,trackCount:1},{wrapperType:'track',kind:'song',collectionId:123,trackId:456,trackName:'Track',discNumber:1,trackNumber:1,trackTimeMillis:1000}]}});}throw Error('Unexpected external '+url);});const {page}=working;await page.goto(base+'/dist/');await settle(page);await page.locator('#case-enabled').check();await settle(page);
 for(let i=0;i<3;i++){await page.locator('#track-add').click();await page.locator('[data-track-field=title]').nth(i).fill('Manual '+i);await page.locator('[data-track-field=title]').nth(i).blur();await settle(page);}const rows=(await state(page)).sets[0].trackList.rows;await page.locator('.track-row').nth(2).getByRole('button',{name:'Move up',exact:true}).click();await settle(page);eq((await state(page)).sets[0].trackList.rows.map(r=>r.id),[rows[0].id,rows[2].id,rows[1].id],'native reorder controls');await page.locator('#track-renumber').click();await settle(page);eq((await state(page)).sets[0].trackList.rows.map(r=>r.no),['1','2','3']);await page.locator('.track-row').nth(1).getByRole('button',{name:'Delete',exact:true}).click();await settle(page);eq((await state(page)).sets[0].trackList.rows.length,2);await page.locator('#track-undo').click();await settle(page);eq((await state(page)).sets[0].trackList.rows.length,3,'undo deletion');
 const valid=await state(page);const validation=await page.evaluate(async valid=>{const {studio}=await import('./app.mjs');let rejected=0;for(const change of [p=>p.mode='unknown',p=>p.sets[0].w='38',p=>p.sets[0].uppercase='true',p=>p.settings.calibrated='false',p=>p.settings.measuredX=NaN]){const p={schema:'md-studio-project/4',...structuredClone(valid)};change(p);try{studio.validateProject(p);}catch{rejected++;}}return rejected;},valid);eq(validation,5,'v3 type/enums rejected');
 // Real upload and v3 validation roundtrip keep image bytes and user typography.
 const upload=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=8;c.height=8;const x=c.getContext('2d');x.fillStyle='#ac032f';x.fillRect(0,0,8,8);return c.toDataURL('image/png').split(',')[1];});await page.locator('#art-file').setInputFiles({name:'roundtrip.png',mimeType:'image/png',buffer:Buffer.from(upload,'base64')});await settle(page);const imgState=await state(page);const roundtrip=await page.evaluate(async s=>{const {studio}=await import('./app.mjs');return studio.validateProject({schema:'md-studio-project/4',...s});},imgState);eq(roundtrip.sets,imgState.sets,'all images/tracks/IDs/fonts preserved');
 await page.locator('#track-sync').focus();await page.keyboard.press('Enter');await settle(page);ok((await page.locator('#case-editor').textContent()).includes('Enable online lookup'),'keyboard sync needs consent');for(const lang of ['en','zh-Hans','zh-Hant','es','fr','ja']){await page.locator('#language').selectOption(lang);ok((await page.locator('#case-editor').textContent()).includes(await page.evaluate(async()=> (await import('./i18n.mjs')).t('caseSyncRequired'))),'existing error translates '+lang);}await page.locator('#language').selectOption('en');page.on('dialog',d=>d.accept());await page.locator('#online-enabled').check();await page.locator('#online-artist').fill('Artist');await page.locator('#online-album').fill('Album');await page.locator('#online-search').click();await page.locator('[data-candidate="0"]').waitFor();await page.locator('[data-candidate="0"]').click();await settle(page);const before=await state(page);holdTrack=true;await page.locator('#track-sync').click();await page.waitForFunction(()=>document.querySelector('#track-sync').disabled);await page.locator('#set-b').click();releaseTrack();await settle(page);await page.waitForTimeout(800);eq((await state(page)).sets,before.sets,'rapid set switching never applies stale response');ok(!(await page.locator('#case-editor').textContent()).includes('Import preview'),'stale import preview suppressed');
 await page.locator('#set-a').click();await settle(page);rate=true;holdTrack=false;await page.locator('#track-sync').click();await page.waitForFunction(()=>document.querySelector('#case-editor').textContent.includes('Track sync failed'),null,{timeout:15000});eq((await state(page)).sets[0].trackList,before.sets[0].trackList,'429 leaves manual edits intact');await page.locator('#language').selectOption('zh-Hans');ok((await page.locator('#case-editor').textContent()).includes('同步失败'),'sync failure translates');
 // Case-only ignores missing, unselected cover assets without requesting them.
 const selective=await page.evaluate(async()=>{const {studio}=await import('./app.mjs'),{sheetCanvas}=await import('./render.mjs'),{defaultAssignments}=await import('./geometry.mjs');const s=studio.getState();s.sets[1].case={profile:'kaih-case-71x60',template:'tracks'};s.sets.forEach(set=>{set.art={type:'upload',data:'data:image/png;base64,broken',name:'unused'};set.profile='custom';set.w=NaN;set.h=Infinity;});let removed=false;try{defaultAssignments(s.sets,'case-only');}catch{removed=true;}if(!removed)throw Error('removed preset accepted');const selected=s.sets.find(x=>x.id===s.settings.sheetSetId)||s.sets[0];Object.assign(selected,{profile:'original',w:38,h:54,sw:58,sh:3.5,art:{type:'sample',seed:0}});s.settings.sheetPreset='case-set';s.settings.sheetSetId=selected.id;s.settings.labelAssignments=defaultAssignments(s.sets,'case-set',selected.id);const result=await sheetCanvas(s.sets,s.settings);return [result.canvas.width,result.canvas.height];});eq(selective,[1181,1748],'case-set exports despite broken art and bad dims on unselected sets');eq(errors,[],'no runtime errors');await working.ctx.close();await writeFile(path.join(out,'results.json'),JSON.stringify({status:'PASS',checks,browser:browser.version(),lookupCount,scope:'Delayed/failed FontFace, native editing/undo/keyboard, strict v3 and image roundtrip, six-language live errors, stale sync/429, selective dependencies'},null,2));console.log(JSON.stringify({status:'PASS',checks,browser:browser.version()}));
}catch(e){await writeFile(path.join(out,'failure.txt'),String(e.stack).replaceAll(root+'/', '').replaceAll('file://', ''));throw e;}finally{await browser.close();server.close();}
