import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/case-label/browser');await mkdir(out,{recursive:true});
const pw=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');let p=url.pathname,dir=root;if(p.startsWith('/baseline/')){dir=path.resolve(root,'../artifacts/case-label/baseline-v0.9.1');p=p.slice('/baseline'.length);}if(p.endsWith('/'))p+='index.html';const file=path.resolve(dir,'.'+p);if(!file.startsWith(dir+'/'))throw Error('outside');res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.png':'image/png','.json':'application/json','.css':'text/css','.woff2':'font/woff2'})[path.extname(file)]||'text/plain');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await pw.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),ctx=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:1000}}),page=await ctx.newPage();
let checks=0;const errors=[],external=[],files=[];const ok=(v,m)=>{assert.ok(v,m);checks++;},eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++;};const hash=b=>createHash('sha256').update(b).digest('hex');
ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));await ctx.route('**/*',r=>{const url=r.request().url();if(url.startsWith(origin)||url.startsWith('blob:'+origin)||url.startsWith('data:'))return r.continue();external.push(url);return r.abort();});
function crc(b){let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function inspect(b,w,h){eq([b.readUInt32BE(16),b.readUInt32BE(20)],[w,h],'PNG dimensions');let at=8,count=0,last='';while(at<b.length){const n=b.readUInt32BE(at),type=b.toString('ascii',at+4,at+8);ok(at+n+12<=b.length,'chunk size');eq(crc(b.subarray(at+4,at+n+8)),b.readUInt32BE(at+n+8),'chunk CRC');if(type==='pHYs'){count++;eq([b.readUInt32BE(at+8),b.readUInt32BE(at+12),b[at+16]],[11811,11811,1],'DPI');}last=type;at+=n+12;}eq([count,last,at],[1,'IEND',b.length],'unique density/end');}
async function settle(p=page){await p.waitForTimeout(350);await p.waitForFunction(()=>!document.querySelector('#export-spine').disabled,{},{timeout:60000});}
async function getState(p=page){return p.evaluate(async()=>{const {studio}=await import('./app.mjs');return studio.getState();});}
async function dl(p,id,name,w,h){const pending=p.waitForEvent('download',{timeout:60000});await p.locator('#'+id).click();const d=await pending;await d.saveAs(path.join(out,name));const b=await readFile(path.join(out,name));if(w)inspect(b,w,h);files.push({path:name,bytes:b.length,sha256:hash(b)});await settle(p);return b;}
async function load(data,p=page){await p.locator('#load-project').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await settle(p);}
async function identity(b,p=page){return p.evaluate(async b64=>{const img=new Image();img.src='data:image/png;base64,'+b64;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d');x.drawImage(img,0,0);const preview=document.querySelector('#preview');if(c.width!==preview.width||c.height!==preview.height)return false;const a=x.getImageData(0,0,c.width,c.height).data,d=preview.getContext('2d').getImageData(0,0,c.width,c.height).data;return a.every((v,i)=>v===d[i]);},b.toString('base64'));}
try{
 await page.goto(origin+'/');await settle();eq(external,[],'no network before consent');const initial=await getState();eq(initial.sets.map(s=>s.id),['set-A','set-B','set-C','set-D']);
 const old=await ctx.newPage();await old.goto(origin+'/baseline/');await settle(old);const legacy=JSON.parse(await dl(old,'save-project','baseline-project-v2.json'));eq(legacy.schema,'md-studio-project/2');await load(legacy);const migrated=await getState();eq(migrated.sets.map(({id,trackList,...s})=>s),legacy.sets,'v2 preserves every historical field');eq(migrated.settings.sheetPreset,'legacy-four');
 for(const mode of ['compat','physical']){await page.locator('#export-mode').selectOption(mode);await old.locator('#export-mode').selectOption(mode);await settle();await settle(old);const a=await dl(page,'export-front','new-front-'+mode+'.png',mode==='compat'?448:449,mode==='compat'?637:638),b=await dl(old,'export-front','baseline-front-'+mode+'.png');eq(hash(a),hash(b),'front byte parity '+mode);}
 for(const id of ['export-spine','export-calibration']){const a=await dl(page,id,'new-'+id+'.png'),b=await dl(old,id,'baseline-'+id+'.png');eq(hash(a),hash(b),'byte parity '+id);}
 for(const count of ['2','4']){await page.locator('#set-count').selectOption(count);await old.locator('#set-count').selectOption(count);await settle();await settle(old);const a=await dl(page,'export-sheet','new-sheet-'+count+'.png',1181,1748),b=await dl(old,'export-sheet','baseline-sheet-'+count+'.png');eq(hash(a),hash(b),'legacy sheet parity '+count);const am=await dl(page,'export-manifest','new-manifest-'+count+'.json'),bm=await dl(old,'export-manifest','baseline-manifest-'+count+'.json');eq(hash(am),hash(bm),'legacy manifest byte parity '+count);}
 const v1={...legacy,schema:'md-studio-project/1',sets:legacy.sets.slice(0,2)};await load(v1);const v1m=await getState();eq(v1m.sets.slice(0,2).map(({id,trackList,...s})=>s),v1.sets,'v1 A/B fields preserved');eq(v1m.settings.setCount,2);eq(v1m.settings.sheetPreset,'legacy-two');eq(v1m.sets.slice(2).map(s=>s.art.seed),[2,3]);
 await page.locator('#case-enabled').check();await settle();await page.locator('#case-preview-button').click();await settle();const empty=await dl(page,'export-case','case-empty.png',839,709);ok(await identity(empty),'case preview/download pixel identity');
 await page.locator('#track-add').click();await page.locator('[data-track-field=title]').fill('第一首 / Coastal Letters');await page.locator('[data-track-field=title]').blur();await settle();await page.locator('[data-track-field=durationMs]').fill('74:00.001');await page.locator('[data-track-field=durationMs]').blur();await settle();await page.locator('#track-capacity').selectOption('74');await settle();ok((await page.locator('#case-editor').textContent()).includes('1 ms'),'1ms overflow warning');eq((await getState()).sets[0].trackList.rows.length,1,'never delete overflow');
 await page.locator('#track-add').click();await page.locator('[data-track-field=title]').nth(1).fill('未知時長 / Unknown');await page.locator('[data-track-field=title]').nth(1).blur();await settle();ok((await page.locator('#case-editor').textContent()).includes('lower bound'),'unknown capacity warning');
 const manual=JSON.parse(await dl(page,'save-project','case-project-v3.json'));eq(manual.schema,'md-studio-project/3');await load(manual);eq((await getState()).sets,manual.sets,'v3 all working edits roundtrip');eq((await getState()).settings,manual.settings,'v3 layout roundtrip');
 const oldBefore=await getState(old);await load(manual,old);eq((await getState(old)).sets,oldBefore.sets,'old reader rejects v3 without state loss');
 const before=await getState();for(const transform of [p=>p.sets[0].id=p.sets[1].id,p=>p.sets[0].trackList.rows[0].durationMs=86400001,p=>p.settings.labelAssignments=[{setId:'missing',kind:'case',copyIndex:0}],p=>p.sets[0].trackList.rows[0].title='x'.repeat(2001),p=>p.sets[0].trackList.rows=Array.from({length:201},(_,i)=>({id:'row-'+i,no:String(i),title:'',durationMs:null,included:true}))]){const invalid=structuredClone(manual);transform(invalid);await load(invalid);eq((await getState()).sets,before.sets,'invalid project keeps state');}
 // Assign different cases; mixed presets use the exact manifest coordinates.
 for(const preset of ['case-only','mixed-compact','easier-cutting']){await page.locator('#sheet-preset').selectOption(preset);await settle();await page.locator('[data-view=sheet]').click();await settle();const png=await dl(page,'export-sheet',preset+'.png',1181,1748);ok(await identity(png),'sheet pixel identity '+preset);const m=JSON.parse(await dl(page,'export-manifest',preset+'.json'));eq(m.schema,'md-studio/2');ok(m.labels.every(l=>l.setId&&l.kind&&Number.isInteger(l.copyIndex)),'label-aware refs');ok(m.labels.find(l=>l.kind==='case').source.url.includes('kai-h'),'source attribution');}
 const withLayout=JSON.parse(await dl(page,'save-project','case-layout-v3.json'));await load(withLayout);eq((await getState()).settings,withLayout.settings,'layout assignments roundtrip');
 // Typography overflow cannot silently clip. Invalid unused custom front does not block case-only.
 const crowded=structuredClone(withLayout);crowded.sets[0].trackList.rows=Array.from({length:14},(_,i)=>({id:'manual-'+i,no:String(i+1),title:'Song '+(i+1),durationMs:1000,included:true}));await load(crowded);await page.locator('#case-preview-button').click();await settle();ok(await page.locator('#export-case').isDisabled(),'14-row case blocked');await page.locator('#language').selectOption('ja');ok(await page.locator('#export-case').isDisabled(),'language refresh preserves invalid export gate');await page.locator('[data-track-field=included]').last().uncheck();await settle();ok(!await page.locator('#export-case').isDisabled(),'13 rows accepted');const thirteen=await dl(page,'export-case','case-13-rows.png',839,709);ok(await identity(thirteen),'13 row identity');
 const info=await page.evaluate(async()=>{const {studio}=await import('./app.mjs'),{caseCanvas}=await import('./render.mjs');const r=await caseCanvas(studio.getState().sets[0]);const d=r.canvas.getContext('2d').getImageData(0,0,r.canvas.width,r.canvas.height).data;return {info:r.info,opaque:d.every((v,i)=>i%4!==3||v===255)};});eq(info.info.typography,{paddingMm:3,headerMm:8,separatorMm:2,footerMm:3,listY:13,listHeight:41,pitchMm:3,fontMm:2.3,rows:13,numberMm:4,titleX:8,titleMm:49,durationX:58,durationMm:10});ok(info.opaque,'no alpha holes');
 await page.locator('#sheet-preset').selectOption('case-only');await settle();await page.locator('#profile').selectOption('custom');await page.locator('#front-w').fill('85');await page.locator('#front-h').fill('120');await settle();ok(!await page.locator('#export-sheet').isDisabled(),'case-only independent invalid unused front');ok(!await page.locator('#export-case').isDisabled(),'standalone independent invalid unused sheet geometry');
 await page.locator('#sheet-preset').selectOption('mixed-compact');await settle();ok(await page.locator('#export-sheet').isDisabled(),'invalid custom mixed layout rejected');ok(!await page.locator('#export-case').isDisabled(),'standalone independent invalid mixed layout');
 // Long Latin/CJK and combining sequences: use actual loaded font and grapheme boundaries.
 const long=structuredClone(withLayout);long.sets[0].trackList.rows=[{id:'long',no:'12345678901234567890',title:'音楽 / Café '.repeat(40),durationMs:null,included:true}];long.settings.sheetPreset='case-only';long.settings.labelAssignments=[{setId:long.sets[0].id,kind:'case',copyIndex:0},{setId:long.sets[1].id,kind:'case',copyIndex:0}];await load(long);await page.locator('#case-preview-button').click();await settle();const longPng=await dl(page,'export-case','case-long-titles.png',839,709);ok(await identity(longPng),'long title identity');const typography=await page.evaluate(async()=>{const {studio}=await import('./app.mjs'),{caseCanvas,graphemes}=await import('./render.mjs');const r=await caseCanvas(studio.getState().sets[0]);return {info:r.info,clusters:graphemes('é👩‍🎤')};});ok(typography.info.truncated,'long title visible truncation');eq(typography.clusters,['é','👩‍🎤'],'combining/emoji grapheme boundaries');
 for(const language of ['en','zh-Hans','zh-Hant','es','fr','ja']){await page.locator('#language').selectOption(language);eq(await page.locator('#track-add').textContent(),await page.evaluate(async()=>{const {t}=await import('./i18n.mjs');return t('caseAdd');}),'translated add '+language);const b=await dl(page,'export-case','case-'+language+'.png',839,709);eq(hash(b),hash(longPng),'UI language leaves printed bytes unchanged '+language);}
 await ctx.setOffline(true);const offline=await dl(page,'export-case','case-offline.png',839,709);eq(hash(offline),hash(longPng),'offline case bytes');await page.locator('[data-view=sheet]').click();await settle();await dl(page,'export-sheet','case-only-offline.png',1181,1748);await ctx.setOffline(false);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'case-mobile.png'),fullPage:true});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'narrow editor no horizontal overflow');await page.setViewportSize({width:1280,height:1000});await page.screenshot({path:path.join(out,'case-desktop.png'),fullPage:true});
 // Missing glyph is a real font gate, not silently rendered emoji fallback.
 const unsupported=structuredClone(long);unsupported.sets[0].trackList.rows[0].title='👩‍🎤';await load(unsupported);await page.locator('#case-preview-button').click();await settle();ok(await page.locator('#export-case').isDisabled(),'missing emoji font glyph blocks export');
 // Mock opt-in metadata and track lookup in same existing client, never audio/artwork.
 await load(long);await page.locator('#language').selectOption('en');const requests=[];let trackCalls=0;await ctx.unroute('**/*');await ctx.route('**/*',async r=>{const u=r.request().url();if(u.startsWith(origin)||u.startsWith('blob:'+origin)||u.startsWith('data:'))return r.continue();requests.push(u);if(u.startsWith('https://itunes.apple.com/search?'))return r.fulfill({json:{results:[{collectionType:'Album',collectionId:123,collectionName:'Album',artistName:'Artist',releaseDate:'2026',trackCount:2}]}});if(u.startsWith('https://itunes.apple.com/lookup?')){trackCalls++;return r.fulfill({json:{results:[{wrapperType:'collection',collectionId:123,trackCount:2},...[2,1].map(i=>({wrapperType:'track',kind:'song',collectionId:123,trackId:i,discNumber:i,trackNumber:1,trackName:'Synced '+i,trackTimeMillis:i===1?1000:undefined}))]}});}external.push(u);return r.abort();});
 page.on('dialog',d=>d.accept());await page.locator('#online-enabled').check();await page.locator('#online-artist').fill('Artist');await page.locator('#online-album').fill('Album');await page.locator('#online-search').click();await page.locator('[data-candidate="0"]').waitFor();await page.locator('[data-candidate="0"]').click();await settle();await page.locator('#track-sync').click();await page.waitForFunction(()=>document.querySelector('#case-editor').textContent.includes('Import preview'));ok((await page.locator('#case-editor').textContent()).includes('disc groups 1, 2'),'multi-disc import preview');eq((await getState()).sets[0].trackList.rows[0].title,long.sets[0].trackList.rows[0].title,'preview never mutates');await page.getByRole('button',{name:'Replace',exact:true}).click();await settle();eq((await getState()).sets[0].trackList.rows.map(r=>r.title),['Synced 1','Synced 2']);
 await page.locator('[data-track-field=title]').first().fill('My edited track');await page.locator('[data-track-field=title]').first().blur();await settle();await page.locator('#track-sync').click();await page.waitForFunction(()=>document.querySelector('#case-editor').textContent.includes('Import preview'));await page.getByRole('button',{name:'Merge, keep manual rows',exact:true}).click();await settle();eq((await getState()).sets[0].trackList.rows[0].title,'My edited track','resync keeps edits');eq(trackCalls,2,'explicit refresh makes track request');ok(requests.every(u=>u.startsWith('https://itunes.apple.com/')),'no audio/cover requests');
 const synced=JSON.parse(await dl(page,'save-project','synced-v3.json'));const countBefore=requests.length;await load(synced);eq(requests.length,countBefore,'project restore never syncs');eq((await getState()).sets,synced.sets,'source snapshots and modified fields preserved');await page.locator('#online-enabled').uncheck();eq((await getState()).sets[0].trackList,synced.sets[0].trackList,'disable online keeps edits');
 console.log('Reached built-tree gate',checks,files.length);await page.goto(origin+'/dist/');await settle();ok(await page.locator('#case-editor').count(),'built modules load');await load(long);await page.locator('#case-preview-button').click();await settle();const built=await dl(page,'export-case','dist-case.png',839,709);eq(hash(built),hash(longPng),'build case byte identity');
 eq(errors,[],'no runtime errors');eq(external,[],'no unexpected network');const report={status:'PASS',checks,browser:browser.version(),files,errors,external,limitations:['Chromium implementation tests, not independent audit','No physical fit/readability acceptance','Live Apple CORS/storefront completeness/terms not verified']};await writeFile(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:'PASS',checks,downloads:files.length,browser:browser.version()}));await old.close();
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(path.join(out,'failure.txt'),String(e.stack).replaceAll(root+'/', '').replaceAll('file://', ''));await writeFile(path.join(out,'failure-diagnostics.json'),JSON.stringify({checks,files,errors,external,state:await getState().catch(()=>null),fontStatus:await page.locator('#font-status').textContent().catch(()=>''),fontDiagnostics:await page.evaluate(async()=>{const {studio}=await import('./app.mjs');return studio.fontDiagnostics();}).catch(()=>null)},null,2));throw e;}finally{await ctx.close();await browser.close();server.close();}
