import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/case-label/engines');await mkdir(out,{recursive:true});
const pw=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname;if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.png':'image/png','.json':'application/json','.css':'text/css','.woff2':'font/woff2'})[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,reports=[];
const crc=b=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
try{for(const engine of ['firefox','webkit']){let browser;const report={engine,status:'PENDING',checks:0,files:[],errors:[],external:[],scope:'Existing Playwright1.48.2 host-supported macOS12 browser binaries; WebKit is not Safari, Firefox131 is not current Firefox.'};const check=(v,m)=>{assert.ok(v,m);report.checks++;};try{browser=await pw[engine].launch({headless:true});report.version=browser.version();const ctx=await browser.newContext({acceptDownloads:true}),page=await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));await ctx.route('**/*',r=>{const u=r.request().url();if(u.startsWith(base+'/')||u.startsWith('blob:'+base+'/')||u.startsWith('data:'))return r.continue();report.external.push(u);return r.abort();});await page.goto(base+'/dist/');await page.waitForFunction(()=>!document.querySelector('#export-spine').disabled,null,{timeout:60000});await page.locator('#case-enabled').check();await page.locator('#case-preview-button').click();await page.waitForFunction(()=>!document.querySelector('#export-case').disabled,null,{timeout:60000});
 const download=async(id,name,w,h)=>{const pending=page.waitForEvent('download',{timeout:60000});await page.locator('#'+id).click();const d=await pending,f=path.join(out,engine+'-'+name+'.png');await d.saveAs(f);const b=await readFile(f);check(b.readUInt32BE(16)===w&&b.readUInt32BE(20)===h,'dimensions');let at=8,n=0;while(at<b.length){const len=b.readUInt32BE(at),type=b.toString('ascii',at+4,at+8);check(crc(b.subarray(at+4,at+8+len))===b.readUInt32BE(at+8+len),'CRC');if(type==='pHYs'){n++;check(b.readUInt32BE(at+8)===11811&&b.readUInt32BE(at+12)===11811&&b[at+16]===1,'DPI');}at+=len+12;}check(n===1,'unique pHYs');check(await page.evaluate(async b64=>{const i=new Image();i.src='data:image/png;base64,'+b64;await i.decode();const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const x=c.getContext('2d');x.drawImage(i,0,0);const p=document.querySelector('#preview');if(p.width!==c.width||p.height!==c.height)return false;const a=x.getImageData(0,0,c.width,c.height).data,d=p.getContext('2d').getImageData(0,0,p.width,p.height).data;return a.every((v,j)=>v===d[j]);},b.toString('base64')),'preview identity');report.files.push(path.basename(f));await page.waitForFunction(()=>!document.querySelector('#export-case').disabled,null,{timeout:60000});return b;};
 await download('export-case','case',839,709);
 const project=await page.evaluate(async()=>{const {studio}=await import('./app.mjs');const state=studio.getState();state.sets[0].trackList.rows=Array.from({length:13},(_,i)=>({id:'engine-row-'+i,no:String(i+1),title:'音楽 / Café / long title '.repeat(i===0?20:1),durationMs:i===12?null:240001,included:true}));return {schema:'md-studio-project/3',sets:state.sets,settings:state.settings,mode:state.mode};});await page.locator('#load-project').setInputFiles({name:'engine-tracks.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await page.waitForTimeout(500);await page.waitForFunction(()=>!document.querySelector('#export-case').disabled,null,{timeout:60000});await download('export-case','case-13-cjk',839,709);for(const preset of ['case-only','mixed-compact','easier-cutting']){await page.locator('#sheet-preset').selectOption(preset);await page.locator('[data-view=sheet]').click();await page.waitForTimeout(400);await page.waitForFunction(()=>!document.querySelector('#export-sheet').disabled,null,{timeout:60000});await download('export-sheet',preset,1181,1748);}
 report.opacity=await page.evaluate(async()=>{const {studio}=await import('./app.mjs'),{caseCanvas}=await import('./render.mjs');const c=(await caseCanvas(studio.getState().sets[0])).canvas;return c.getContext('2d').getImageData(0,0,c.width,c.height).data.every((v,i)=>i%4!==3||v===255);});check(report.opacity,'opaque case');check(!report.errors.length&&!report.external.length,'runtime/network');report.status='PASS';await ctx.close();}catch(e){report.status='FAIL';report.failure=String(e.stack);}finally{if(browser)await browser.close();reports.push(report);await writeFile(path.join(out,engine+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}}}finally{server.close();}if(reports.some(r=>r.status!=='PASS'))process.exitCode=1;
