import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/autocomplete-feature');
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const server=createServer(async(req,res)=>{try{let file=new URL(req.url,'http://localhost').pathname;if(file.endsWith('/'))file+='index.html';res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.css':'text/css','.woff2':'font/woff2','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(await readFile(path.join(root,file)));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();
const jay='a223958d-5c56-4b2c-a30a-87e357bc121b',debut='877e9870-1b55-3153-8875-139cfe468679',wrong='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',beatles='b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d',red='5bb120e2-fe76-33cc-a4bb-8f56f2fd3d67';
let scenario='TW',png,failCover=false;const requests=[],errors=[],proof=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await context.route('**/*',async route=>{const url=route.request().url();if(url.startsWith(base)||url.startsWith('data:')||url.startsWith('blob:'))return route.continue();requests.push({url,time:Date.now(),scenario});const headers={'Access-Control-Allow-Origin':'*','Content-Type':'application/json'};const b=scenario==='US',arid=b?beatles:jay,name=b?'The Beatles':'周杰倫',q=new URL(url).searchParams.get('query');let body;
if(url.includes('itunes.apple.com'))body={results:[{collectionType:'Album',collectionId:b?6818181173:scenario==='TW'?535790918:535790919,collectionName:b?'The Beatles 1962 - 1966 (Remastered)':scenario==='TW'?'同名專輯':'杰倫',artistName:name,releaseDate:b?'1973-01-01':'2000-11-06'}]};
else if(url.includes('/artist/'))body={artists:[{id:arid,name}]};
else if(url.includes('musicbrainz.org')){const fallback=!q.includes('releasegroup:'),normalized=q.includes('1962\\-1966'),rows=fallback||normalized?[{id:b?red:debut,title:b?'1962–1966':'Jay',year:b?'1973':'2000',note:b?'The Red Album':''},{id:wrong,title:b?'1967–1970':'Unrelated later album',year:'2005',note:'Compilation'}]:scenario==='JP'?[{id:wrong,title:'Unrelated later album',year:'2005'}]:[];body={count:rows.length,'release-groups':rows.map(v=>({id:v.id,title:v.title,disambiguation:v.note,'primary-type':'Album','secondary-types':b?['Compilation']:[],'first-release-date':v.year,'artist-credit':[{artist:{id:arid,name}}]}))};}
else if(url.includes('coverartarchive.org')){if(failCover)return route.fulfill({status:404,headers,body:'{}'});body={images:[{front:true,thumbnails:{1200:'https://archive.org/crossmatch-fixture.png'}}]};}
else if(url==='https://archive.org/crossmatch-fixture.png')return route.fulfill({headers:{'Content-Type':'image/png'},body:png});else return route.abort();return route.fulfill({headers,body:JSON.stringify(body)});});
const stage=(name,status)=>page.waitForSelector(`[data-stage="${name}"][data-status="${status}"]`,{timeout:60000});
async function search(){await page.locator('#online-store').selectOption(scenario);await page.locator('#online-artist').dispatchEvent('compositionstart');await page.locator('#online-artist').fill(scenario==='US'?'The Beatles':'周杰倫');await page.locator('#online-album').fill(scenario==='US'?'1962':scenario==='TW'?'同名專輯':'杰倫');await page.locator('#online-artist').dispatchEvent('compositionend');await page.locator('#online-search').click();await stage('search','done');await page.locator('[data-candidate="0"]').click();await stage('selected','done');}
try{await page.goto(base);await page.waitForFunction(()=>!document.getElementById('export-front').disabled);assert.equal(requests.length,0);png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=600;c.getContext('2d').fillRect(0,0,600,600);return c.toDataURL().split(',')[1];}),'base64');await page.locator('#online-enabled').check();
for(const country of ['TW','JP','US']){scenario=country;await search();const from=requests.length;await page.locator('#online-cover').click();await stage('match','waiting');const rows=await page.locator('[data-candidate]').allTextContents();assert(rows[0].includes(country==='US'?'1962–1966':'Jay'));assert.equal(requests.slice(from).filter(v=>v.url.includes('coverartarchive')).length,0);assert.equal(await page.locator('[data-stage=match]').getAttribute('data-status'),'waiting');const text=await page.locator('#online-message').innerText();if(country!=='US')assert(text.includes('No automatic match'));const localeProof=[];for(const lang of ['en','zh-Hans','zh-Hant','es','fr','ja']){await page.locator('#language').selectOption(lang);const localized=await page.locator('#online-message').innerText();assert(localized&&localized!=='fallbackChoice'&&localized!=='matchChoice');localeProof.push({lang,text:localized});}await page.locator('#language').selectOption('en');await page.locator('#online-lookup').screenshot({path:path.join(out,`crossmatch-${country}.png`)});await page.locator('[data-candidate="0"]').click();await stage('import','done');assert.equal(await page.locator('#album').inputValue(),country==='TW'?'同名專輯':country==='JP'?'杰倫':'The Beatles 1962 - 1966 (Remastered)');proof.push({country,rows,text,locales:localeProof,requests:requests.slice(from)});
// Repeat selection/import: mapping survives re-selection and reload of Lookup.
await page.reload();await page.waitForFunction(()=>!document.getElementById('export-front').disabled);await page.locator('#online-enabled').check();await search();const repeat=requests.length;await page.locator('#online-cover').click();await stage('import','done');assert.equal(requests.slice(repeat).filter(v=>v.url.includes('musicbrainz.org')).length,0);assert.equal(await page.locator('[data-candidate]').count(),0);proof.at(-1).cacheHitRequests=requests.slice(repeat);
}
// Cached cover failure invalidates mapping; retry through import button requires new explicit match.
failCover=true;await page.locator('#online-enabled').uncheck();await page.locator('#online-enabled').check();await search();await page.locator('#online-cover').click();await stage('cover','error');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('md-confirmed-matches-v1')).some(e=>e.mbid==='5bb120e2-fe76-33cc-a4bb-8f56f2fd3d67')),false);failCover=false;await page.locator('#online-cover').click();await stage('match','waiting');assert.equal(await page.locator('[data-candidate]').count(),1);
const mb=requests.filter(v=>v.url.includes('musicbrainz.org'));const gaps=mb.slice(1).map((v,i)=>v.time-mb[i].time);assert(gaps.every(v=>v>=1200));assert.deepEqual(errors,[]);await writeFile(path.join(out,'crossmatch-browser-results.json'),JSON.stringify({status:'PASS',proof,mbGaps:gaps,errors,defaultOffZeroEgress:true,invalidation:true},null,2));console.log(JSON.stringify({status:'PASS',cases:proof.length,cacheHits:proof.length,minMbGap:Math.min(...gaps),sixLanguageSpot:true}));
}finally{await browser.close();server.close();}
