import assert from 'node:assert/strict';
import {Lookup,matchTitle,selfTitle,relatedTitle,ConfirmedMappings,RateLimiter} from '../online.mjs';
const beatles='b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d',jay='a223958d-5c56-4b2c-a30a-87e357bc121b',red='5bb120e2-fe76-33cc-a4bb-8f56f2fd3d67',debut='877e9870-1b55-3153-8875-139cfe468679';
for(const dash of ['-','–','—','‐','−',' '])for(const space of ['',' '])assert.equal(matchTitle(`The Beatles 1962${space}${dash}${space}1966 (Remastered)`,'The Beatles'),'1962-1966');
assert.equal(matchTitle('The Beatles','The Beatles'),'The Beatles');assert.equal(matchTitle('Song (For You)','Artist'),'Song (For You)');assert.equal(matchTitle('A+B 1962 - 1966','A+B'),'1962-1966');
for(const t of ['同名專輯','同名专辑','self-titled','Self Titled Album','eponymous'])assert(selfTitle(t));assert(!selfTitle('Same Title'));assert(!relatedTitle('1962–1966 / 1967–1970','1962-1966'));assert(relatedTitle('1962–1966','1962-1966'));
export const cases=[{id:'6818181173',country:'US',album:'The Beatles 1962 - 1966 (Remastered)',artist:'The Beatles',year:'1973',arid:beatles,mbid:red,title:'1962–1966',note:'The Red Album'},{id:'535790918',country:'TW',album:'同名專輯',artist:'周杰倫',year:'2000',arid:jay,mbid:debut,title:'Jay'},{id:'jp-fixture',country:'JP',album:'杰倫',artist:'周杰倫',year:'2000',arid:jay,mbid:debut,title:'Jay'}];
const evidence=[];
for(const c of cases){const requests=[];let now=0;const starts=[],l=new Lookup({mbLimiter:new RateLimiter('fixture',1300,{now:()=>now,wait:async ms=>now+=ms,storage:null,locks:null}),fetcher:async url=>{starts.push(now);const q=new URL(url).searchParams.get('query');requests.push(q);let body;if(url.includes('/artist/'))body={artists:[{id:c.arid,name:c.artist}]};else{const normalized=q.includes('1962\\-1966'),fallback=!q.includes('releasegroup:');const unrelated={id:'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',title:'周杰伦地表最强世界巡回演唱会',year:'2019'};const rows=normalized||fallback?[{id:c.mbid,title:c.title,year:c.year,note:c.note}]:c.country==='JP'?[unrelated]:[];body={count:rows.length,'release-groups':rows.map(v=>({id:v.id,title:v.title,disambiguation:v.note,'primary-type':'Album','secondary-types':c.arid===beatles?['Compilation']:[], 'first-release-date':v.year,'artist-credit':[{artist:{id:c.arid,name:c.artist}}]}))};}return new Response(JSON.stringify(body));}});l.enable(true);const result=await l.crossMatch({...c,source:'itunes'});assert.equal(result.candidates[0].id,c.mbid);assert.equal(result.fallback,c.arid!==beatles);assert(starts.slice(1).every((v,i)=>v-starts[i]>=1200));if(selfTitle(c.album))assert(requests.every(q=>!q.includes('releasegroup:')));assert(requests.every(q=>!q.includes('releasegroup:()')));evidence.push({case:c.album,country:c.country,candidates:result.candidates,requests,starts,fallback:result.fallback});}
const store=new Map(),storage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)};let clock=1000;const cache=new ConfirmedMappings(storage,()=>clock),c={...cases[1],source:'itunes'};assert.equal(cache.get(c),'');cache.set(c,debut);assert.equal(cache.get(c),debut);assert.equal(cache.get({...c,country:'JP'}),'');assert.equal(cache.get({...c,album:'changed'}),'');cache.set(c,debut);clock+=31*86400000;assert.equal(cache.get(c),'');clock=1000;cache.set(c,debut);cache.remove(c);assert.equal(cache.get(c),'');assert.doesNotThrow(()=>new ConfirmedMappings({getItem(){throw Error()},setItem(){throw Error()}}).set(c,debut));
console.log(JSON.stringify({status:'PASS',cases:evidence,cache:'storefront/fingerprint/TTL/invalidation/storage failure verified'},null,2));
