import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
import {LANGUAGES,fontChoices} from '../i18n.mjs';
const root=path.resolve(process.env.FONT_TEST_ROOT||path.resolve(import.meta.dirname,'..')),out=path.resolve(import.meta.dirname,'../../artifacts/minesweep');await mkdir(out,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');let assertions=0;const check=(v,m)=>{assert.ok(v,m);assertions++;};
const manifest=JSON.parse(await readFile(path.join(root,'assets/fonts/manifest.json')));check(Object.keys(manifest).length===9,'nine bundled faces');let total=0;
for(const [key,f] of Object.entries(manifest)){const b=await readFile(path.join(root,'assets/fonts',f.file));check(sha(b)===f.sha256,key+' binary hash');check(b.length===f.bytes,key+' size');check(b.toString('ascii',0,4)==='wOF2',key+' WOFF2');const license=await readFile(path.join(root,'assets/fonts',f.licenseFile),'utf8');check(license.includes('SIL OPEN FONT LICENSE Version 1.1'),key+' OFL');total+=b.length;}
check(total<25*1024*1024,'aggregate fonts below 25 MiB');
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const server=createServer(async(req,res)=>{try{let rel=new URL(req.url,'http://localhost').pathname;if(rel.endsWith('/'))rel+='index.html';const p=path.resolve(root,'.'+rel);if(!p.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.svg':'image/svg+xml','.png':'image/png'})[path.extname(p)]||'text/plain');res.end(await readFile(p));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),errors=[],results=[];
page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>r.request().url().startsWith(base)||r.request().url().startsWith('blob:'+base)?r.continue():r.abort());
async function ready(){await page.waitForTimeout(200);await page.waitForFunction(()=>!document.querySelector('#export-front').disabled,null,{timeout:60000});}
try{await page.goto(base+'/');await ready();await page.locator('#export-mode').selectOption('physical');await ready();const diagnostics=await page.evaluate(async()=> (await import('./render.mjs')).fontDiagnostics());check(Object.keys(diagnostics).length===9&&Object.values(diagnostics).every(f=>f.loaded),'all real FontFaces loaded');
const initial=await page.evaluate(async()=> (await import('./app.mjs')).studio.getState());
for(const lang of LANGUAGES){await page.locator('#language').selectOption(lang);for(const role of ['latin','cjk']){const actual=await page.locator('#'+role+' option').evaluateAll(ns=>ns.map(n=>n.value));check(JSON.stringify(actual)===JSON.stringify(fontChoices(role,initial.sets[0][role],lang).map(c=>c.key)),lang+' '+role+' selector');}check(JSON.stringify(await page.evaluate(async()=> (await import('./app.mjs')).studio.getState()))===JSON.stringify(initial),lang+' state unchanged');}
for(const [lang,role,key,sample] of [['en','latin','source-sans','Été Canción'],['zh-Hans','cjk','noto-sc-regular','音乐录音'],['zh-Hant','cjk','noto-tc','音樂錄音'],['ja','cjk','noto-jp','日本語の音楽']]){await page.locator('#language').selectOption(lang);await page.locator('#'+role).selectOption(key);await page.locator('#album').fill(sample);await page.locator('#artist').fill('');await ready();const waiting=page.waitForEvent('download');await page.locator('#export-front').click();const d=await waiting,p=path.join(out,'font-'+key+'.png');await d.saveAs(p);const b=await readFile(p);check(b.readUInt32BE(16)===449&&b.readUInt32BE(20)===638,key+' actual PNG');await page.locator('#language').selectOption('fr');check(await page.locator('#'+role).inputValue()===key,key+' retained across language change');results.push({key,lang,sha256:sha(b),bytes:b.length});}
check(errors.length===0,'no runtime errors');const report={status:'PASS',root:process.env.FONT_TEST_ROOT?'published build':'app',assertions,totalFontBytes:total,diagnostics,exports:results,errors};await writeFile(path.join(out,process.env.FONT_TEST_ROOT?'published-font-results.json':'font-results.json'),JSON.stringify(report,null,2));console.log('PASS fonts',assertions,'assertions; actual exports and all nine FontFaces');}finally{await browser.close();await new Promise(r=>server.close(r));}
