import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/four-set');await mkdir(out,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'/Users/xzhou/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core');
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname.replace(/^\/studio\//,'/');if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw Error('outside');res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.png':'image/png','.json':'application/json','.css':'text/css','.woff2':'font/woff2'})[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:1000}}),page=await context.newPage();
const errors=[],external=[],files=[];let assertions=0;const check=(v,m)=>{assert.ok(v,m);assertions++;};page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>{const u=r.request().url();if(u.startsWith(base)||u.startsWith('blob:'+base)||u.startsWith('data:'))return r.continue();external.push(u);return r.abort();});
// Independent CRC implementation: no production PNG or geometry imports.
function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function inspect(b,w,h){check(b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),'PNG signature');check(b.readUInt32BE(16)===w&&b.readUInt32BE(20)===h,'PNG dimensions');let densities=0,last='',at=8;while(at<b.length){const n=b.readUInt32BE(at),type=b.toString('ascii',at+4,at+8);check(at+12+n<=b.length,'chunk bounds');check(crc(b.subarray(at+4,at+8+n))===b.readUInt32BE(at+8+n),'CRC '+type);if(type==='pHYs'){densities++;check(n===9&&b.readUInt32BE(at+8)===11811&&b.readUInt32BE(at+12)===11811&&b[at+16]===1,'pHYs 300dpi');}last=type;at+=12+n;}check(densities===1&&last==='IEND'&&at===b.length,'unique pHYs and complete PNG');}
async function settle(){await page.waitForTimeout(250);await page.waitForFunction(()=>!document.querySelector('#export-front').disabled,{},{timeout:60000});}
async function state(){return page.evaluate(async()=>{const {studio}=await import('./app.mjs');return studio.getState();});}
async function download(id,name,w,h){const wait=page.waitForEvent('download',{timeout:60000});await page.locator('#'+id).click();const d=await wait;await d.saveAs(path.join(out,name));const b=await readFile(path.join(out,name));if(w)inspect(b,w,h);files.push({path:name,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex'),suggestedFilename:d.suggestedFilename()});await settle();return b;}
async function load(data){await page.locator('#load-project').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await settle();}
async function identity(b){return page.evaluate(async(png)=>{const img=new Image();img.src='data:image/png;base64,'+png;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const p=document.querySelector('#preview');if(c.width!==p.width||c.height!==p.height)return false;const a=ctx.getImageData(0,0,c.width,c.height).data,d=p.getContext('2d').getImageData(0,0,p.width,p.height).data;return a.every((v,i)=>v===d[i]);},b.toString('base64'));}
try{
 await page.goto(base+'/studio/');await settle();const initial=await state();check(initial.sets.length===4&&initial.settings.setCount===4,'four-set default');check(initial.settings.paper==='selphy'&&!initial.settings.calibrated,'default 100x148 no compensation');
 await page.locator('[data-view=sheet]').click();await settle();const sample=await download('export-sheet','four-set-procedural-cover.png',1181,1748);check(await identity(sample),'full four-set preview pixel-identical to actual download');await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'four-set-default-desktop.png'),fullPage:true});
 const manifest=JSON.parse(await download('export-manifest','four-set-geometry.json'));check(manifest.sets.length===4,'eight-label manifest');const rects=[];for(let i=0;i<4;i++){const ls=manifest.sets[i].labels;check(JSON.stringify(ls[0].designMm)===JSON.stringify({x:i%2?53:9,y:i<2?6:62,width:38,height:54}),'front anchor '+i);check(JSON.stringify(ls[1].designMm)===JSON.stringify({x:21,y:118+i*5.5,width:58,height:3.5}),'spine anchor '+i);for(const l of ls){const r=l.renderedMm;check(r.x>=6&&r.y>=6&&r.x+r.width<=94&&r.y+r.height<=142,'6mm safety');check(l.cutline.placement==='inside'&&l.cutline.widthMm===.1,'inside 0.1mm cut');const px=m=>Math.round(m*300/25.4);check(JSON.stringify(l.rectPx)===JSON.stringify({x:px(r.x),y:px(r.y),width:px(r.x+r.width)-px(r.x),height:px(r.y+r.height)-px(r.y)}),'absolute-edge rounding');rects.push(r);}}for(let i=0;i<8;i++)for(let j=i+1;j<8;j++){const a=rects[i],b=rects[j];check(!(a.x<b.x+b.width&&b.x<a.x+a.width&&a.y<b.y+b.height&&b.y<a.y+a.height),'no label overlap');}
 const raster=await page.evaluate(()=>{const c=document.querySelector('#preview'),x=c.getContext('2d'),p=300/25.4,hashes=[],boxes=[];for(let i=0;i<4;i++){const rx=i%2?53:9,ry=i<2?6:62;const art=x.getImageData(Math.round((rx+2)*p),Math.round((ry+7)*p),Math.round(34*p),Math.round(34*p)).data;let hash=2166136261;for(const v of art)hash=Math.imul(hash^v,16777619)>>>0;hashes.push(hash);for(const r of [{x:rx,y:ry,w:38,h:54},{x:21,y:118+i*5.5,w:58,h:3.5}]){const left=Math.round(r.x*p),top=Math.round(r.y*p),w=Math.round((r.x+r.w)*p)-left,h=Math.round((r.y+r.h)*p)-top,d=x.getImageData(left-2,top-2,w+4,h+4);let minX=1e9,minY=1e9,maxX=-1,maxY=-1;for(let y=0;y<d.height;y++)for(let xx=0;xx<d.width;xx++){const k=(y*d.width+xx)*4;if(d.data[k]<245||d.data[k+1]<245||d.data[k+2]<245){minX=Math.min(minX,xx);minY=Math.min(minY,y);maxX=Math.max(maxX,xx);maxY=Math.max(maxY,y);}}boxes.push(Math.abs(minX-2)<=1&&Math.abs(minY-2)<=1&&Math.abs(maxX-(w+1))<=1&&Math.abs(maxY-(h+1))<=1);}}return {hashes,boxes};});check(new Set(raster.hashes).size===4,'four distinct rendered covers');check(raster.boxes.length===8&&raster.boxes.every(Boolean),'eight actual label pixel bounds');
 await page.locator('[data-view=label]').click();await page.locator('#export-mode').selectOption('physical');await settle();const faces=['noto-sans','noto-serif','wenkai','noto-sans'];
 for(let i=0;i<4;i++){await page.locator('#set-'+'abcd'[i]).click();await settle();await page.locator('#album').fill('ABCD'[i]+' / 独立专辑');await page.locator('#artist').fill('Artist '+'ABCD'[i]);await page.locator('#year').fill(String(2020+i));await page.locator('#cjk').selectOption(faces[i]);await page.locator('#latin').selectOption(i%2?'b612':'atkinson');await page.locator('#uppercase').setChecked(i%2===0);await page.locator('#hide-header').setChecked(i===2);await page.locator('[name=theme][value='+ (i%2?'light':'dark')+']').check();await settle();await download('export-front','independent-'+'ABCD'[i]+'.png',449,638);await download('export-spine','spine-'+'ABCD'[i]+'.png',685,41);}
 const configured=await state();for(let i=0;i<4;i++){check(configured.sets[i].album==='ABCD'[i]+' / 独立专辑','text independent '+i);check(configured.sets[i].cjk===faces[i]&&configured.sets[i].hideHeader===(i===2),'fonts/header independent '+i);check(configured.sets[i].art.seed===i,'images independent '+i);}
 // Real upload on D; switching tabs and clearing C must not replace D/A/B.
 const upload=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=600;c.height=300;const x=c.getContext('2d');x.fillStyle='#fd0081';x.fillRect(0,0,600,300);return c.toDataURL('image/png').split(',')[1];});await page.locator('#art-file').setInputFiles({name:'D-local-cover.png',mimeType:'image/png',buffer:Buffer.from(upload,'base64')});await settle();await page.locator('#set-c').click();await page.locator('#clear-art').click();await settle();const beforeSave=await state();check(beforeSave.sets[3].art.type==='upload'&&beforeSave.sets[2].art.type==='none'&&beforeSave.sets[0].art.seed===0&&beforeSave.sets[1].art.seed===1,'upload/clear independent across four sets');
 const saved=JSON.parse(await download('save-project','four-set-project.json'));check(saved.schema==='md-studio-project/2'&&saved.sets.length===4,'new four-set schema');await page.locator('#album').fill('modified');await load(saved);check(JSON.stringify((await state()).sets)===JSON.stringify(saved.sets),'four-set round-trip all fields/images');
 await page.locator('#set-count').selectOption('2');await settle();await page.locator('[data-view=sheet]').click();await settle();const two=await download('export-sheet','two-set-preserved.png',1181,1748);check(await identity(two),'two-set preview download identity');check(JSON.stringify((await state()).sets)===JSON.stringify(saved.sets),'2-mode retains C/D');await page.locator('#set-count').selectOption('4');await settle();const restored=await download('export-sheet','four-set-custom-content.png',1181,1748);check(await identity(restored),'configured four-set identity');
 // Actual published two-set app's save control, not only a synthesized legacy object.
 const oldRoot=path.resolve(root,'../artifacts/four-set/legacy-app');const oldServer=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname;if(p.endsWith('/'))p+='index.html';const f=path.resolve(oldRoot,'.'+p);if(!f.startsWith(oldRoot+'/'))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.png':'image/png','.json':'application/json','.woff2':'font/woff2','.css':'text/css'})[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>oldServer.listen(0,'127.0.0.1',r));const oldContext=await browser.newContext({acceptDownloads:true}),op=await oldContext.newPage();let legacy;try{await op.goto(`http://127.0.0.1:${oldServer.address().port}/`);await op.waitForFunction(()=>!document.querySelector('#export-front').disabled,{},{timeout:60000});const wait=op.waitForEvent('download');await op.locator('#save-project').click();const d=await wait;await d.saveAs(path.join(out,'legacy-actual-project.json'));legacy=JSON.parse(await readFile(path.join(out,'legacy-actual-project.json')));}finally{await oldContext.close();oldServer.close();}
 check(legacy.schema==='md-studio-project/1'&&legacy.sets.length===2,'real prior app legacy fixture');await load(legacy);const migrated=await state();check(migrated.sets.length===4&&migrated.settings.setCount===2,'legacy migrates safely preserving 2-mode');check(JSON.stringify(migrated.sets.slice(0,2))===JSON.stringify(legacy.sets),'legacy A/B preserved exactly');check(migrated.sets[2].art.seed===2&&migrated.sets[3].art.seed===3,'migration adds independent C/D');await download('export-sheet','legacy-migrated-two-set.png',1181,1748);await page.locator('#set-count').selectOption('4');await settle();await download('export-sheet','legacy-migrated-four-set.png',1181,1748);
 // Invalid four-set custom sizes refuse export, never shrink; standalone remains valid.
 await page.locator('[data-view=label]').click();await page.locator('#profile').selectOption('custom');await page.locator('#front-w').fill('45');await settle();check(await page.locator('#export-sheet').isDisabled(),'custom width collision blocks sheet');check(!await page.locator('#export-front').isDisabled(),'collision does not block standalone');await download('export-front','custom-valid-standalone.png',531,638);check((await state()).sets[0].w===45,'no auto-shrink');await page.locator('#front-w').fill('38');await page.locator('#front-h').fill('57');await settle();check(await page.locator('#export-sheet').isDisabled(),'custom height collision blocks');await page.locator('#front-h').fill('54');await page.locator('#spine-h').fill('6');await settle();check(await page.locator('#export-sheet').isDisabled(),'spine collision blocks');await page.locator('#spine-h').fill('3.5');await page.locator('#set-d').click();await page.locator('#spine-w').fill('75');await settle();check(await page.locator('#export-sheet').isDisabled(),'6mm margin violation blocks');await page.locator('#spine-w').fill('58');await settle();check(!await page.locator('#export-sheet').isDisabled(),'valid layout recovered');
 await load(saved);await page.locator('[data-view=sheet]').click();await settle();await context.setOffline(true);const offline=await download('export-sheet','four-set-offline.png',1181,1748);check(offline.equals(restored),'offline sheet byte-identical');await context.setOffline(false);await page.locator('#paper').selectOption('inch');await settle();await download('export-sheet','four-set-4x6.png',1200,1800);await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'four-set-mobile.png'),fullPage:true});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'four tabs mobile no overflow');check(await page.locator('.set-tabs button').evaluateAll(bs=>bs.every(b=>b.scrollWidth<=b.clientWidth)),'four mobile tab labels fit');
 await page.goto(base+'/dist/');await settle();check((await state()).sets.length===4,'candidate dist uses four sets');await page.locator('[data-view=sheet]').click();await settle();const built=await download('export-sheet','candidate-dist-four-set.png',1181,1748);check(built.equals(sample),'candidate dist actual download identical');check(errors.length===0&&external.length===0,'no runtime errors/external requests');
 const report={status:'PASS',assertions,browser:browser.version(),raster,files,runtimeErrors:errors,externalRequests:external,scope:'Local Chromium implementation verification; not independent astra audit or physical printer acceptance.'};await writeFile(path.join(out,'test-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,assertions,browser:report.browser,downloads:files.length},null,2));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(path.join(out,'failure.txt'),String(e.stack));throw e;}finally{await context.close();await browser.close();server.close();}
