import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/himd');await mkdir(out,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname.replace(/^\/studio\//,'/');if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.png':'image/png','.json':'application/json','.css':'text/css','.woff2':'font/woff2'})[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({acceptDownloads:true}),page=await context.newPage();let assertions=0;const files=[],results=[],errors=[],requests=[];const check=(v,m)=>{assert.ok(v,m);assertions++;};page.on('console',m=>{if(m.text().startsWith('HiMD crop diff'))console.log(m.text());});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await context.route('**/*',r=>r.request().url().startsWith(base)||r.request().url().startsWith('blob:'+base)?r.continue():r.abort());
async function settle(){await page.waitForTimeout(230);await page.waitForFunction(()=>!document.querySelector('#export-front').disabled&&!document.querySelector('#export-sheet').disabled&&!document.querySelector('#export-spine').disabled,{},{timeout:60000});}
async function state(){return page.evaluate(async()=> (await import('./app.mjs')).studio.getState());}
async function load(p){await page.locator('#load-project').setInputFiles({name:'himd-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await settle();}
function crc(b){let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
async function dl(id,name,size){const wait=page.waitForEvent('download');await page.locator('#'+id).click();const d=await wait;await d.saveAs(path.join(out,name));const b=await readFile(path.join(out,name));if(size){check(b.readUInt32BE(16)===size[0]&&b.readUInt32BE(20)===size[1],'unchanged PNG geometry '+name);let phys=0;for(let at=8;at<b.length;){const n=b.readUInt32BE(at),t=b.toString('ascii',at+4,at+8);check(crc(b.subarray(at+4,at+8+n))===b.readUInt32BE(at+8+n),'independent CRC '+t);if(t==='pHYs'){phys++;check(b.readUInt32BE(at+8)===11811&&b.readUInt32BE(at+12)===11811&&b[at+16]===1,'300dpi');}at+=n+12;}check(phys===1,'unique density');}files.push({path:name,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')});await settle();return b;}
async function audit(b,kind,project){return page.evaluate(async({b64,kind,project})=>{
 const ppm=300/25.4;async function image(src){const i=new Image();i.src=src;await i.decode();return i;}
 const img=await image('data:image/png;base64,'+b64),c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d');x.drawImage(img,0,0);
 const e=document.createElement('canvas');e.width=c.width;e.height=c.height;const ex=e.getContext('2d'),md=await image(new URL('./assets/branding/minidisc.png',location.href)),bar=await image(new URL('./assets/branding/hi-md.png',location.href));
 const frame=document.createElement('canvas');frame.width=106;frame.height=43;const f=frame.getContext('2d');f.fillStyle='white';f.fillRect(5,5,96,33);for(const [sx,sy,sw,sh,dx,dy,dw,dh] of [[0,0,5,5,0,0,5,5],[39,0,5,5,101,0,5,5],[0,38,5,5,0,38,5,5],[39,38,5,5,101,38,5,5],[5,0,34,5,5,0,96,5],[5,38,34,5,5,38,96,5],[0,5,5,33,0,5,5,33],[39,5,5,33,101,5,5,33]])f.drawImage(md,sx,sy,sw,sh,dx,dy,dw,dh);
 const {sheetManifest}=await import('./geometry.mjs');const m=sheetManifest(project.sets.slice(0,project.settings.setCount),project.settings);const rects=kind==='sheet'?m.sets.flatMap((s,i)=>s.labels.map(l=>({...l.renderedMm,kind:l.kind,set:project.sets[i]}))):[{x:0,y:0,width:c.width/ppm,height:c.height/ppm,kind,set:project.sets[0]}];const checks=[],diffs=[];
 function crop(left,top,w,h){const a=x.getImageData(left,top,w,h).data,b=ex.getImageData(left,top,w,h).data;let channels=0,max=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i]){channels++;max=Math.max(max,Math.abs(a[i]-b[i]));}if(channels){diffs.push({left,top,w,h,channels,max});console.log('HiMD crop diff',left,top,w,h,channels,max);}return channels===0;}
 for(const r of rects){ex.save();ex.scale(ppm,ppm);ex.translate(r.x,r.y);ex.scale(1,1);ex.beginPath();ex.rect(0,0,r.width,r.height);ex.clip();ex.fillStyle=r.set.theme==='dark'?'#231F20':'white';ex.fillRect(0,0,r.width,r.height);if(r.kind==='front'){const lw=44/11.811,lh=43/11.811,xx=38-2-lw,yy=(5-lh)/2;if(!r.set.hideHeader){ex.drawImage(md,xx,yy,lw,lh);if(r.set.hiMD){const fw=106/11.811,fh=43/11.811,fx=xx-.5-fw,fy=(5-fh)/2,t=2/11.811,pad=5/11.811;ex.drawImage(frame,fx,fy,fw,fh);ex.drawImage(bar,fx+(106-31*272/88)/2/11.811,fy+pad,(31*272/88)/11.811,31/11.811);}}ex.restore();if(!r.set.hideHeader){checks.push({what:'MiniDisc unchanged',rect:[Math.floor((r.x+xx)*ppm),Math.floor((r.y+yy)*ppm),45,44]});checks.push({what:r.set.hiMD?'Hi-MD left':'unchecked no front Hi-MD',rect:[Math.floor((r.x+xx-106/11.811-.5)*ppm),Math.floor((r.y+(5-43/11.811)/2)*ppm),108,44]});}}else{const lw=6.8,lh=lw*88/272,xx=r.width-1.5-lw,yy=(r.height-lh)/2;if(r.set.hiMD)ex.drawImage(bar,xx,yy,lw,lh);ex.restore();if(r.set.hiMD)checks.push({what:'right spine bar',rect:[Math.ceil((r.x+xx)*ppm),Math.ceil((r.y+yy)*ppm),Math.floor(lw*ppm)-1,Math.floor(lh*ppm)-1]});}}
 // Read back only after all draws: interleaved getImageData changes Chromium's GPU/CPU interpolation path.
 for(const c of checks)c.ok=crop(...c.rect);
 const preview=document.querySelector(kind==='spine'?'#spine-preview':'#preview');let parity=preview.width===c.width&&preview.height===c.height;if(parity){const a=preview.getContext('2d').getImageData(0,0,c.width,c.height).data,b=x.getImageData(0,0,c.width,c.height).data;parity=a.every((v,i)=>v===b[i]);}
 // Independent visible-ink midpoint and text/logo separation; exclude cut border and bar.
 const bands=[];for(const r of rects.filter(r=>r.kind==='spine')){const right=r.set.hiMD?r.width-1.5-6.8-1:r.width-1.5;const data=x.getImageData(Math.round(r.x*ppm),Math.round(r.y*ppm),Math.round(r.width*ppm),Math.round(r.height*ppm));let min=Infinity,max=-1,maxX=-1;for(let yy=3;yy<data.height-3;yy++)for(let xx=12;xx<Math.floor(right*ppm);xx++){const k=(yy*data.width+xx)*4,fg=r.set.theme==='dark'?data.data[k]>140&&data.data[k+1]>140&&data.data[k+2]>140:data.data[k]<120&&data.data[k+1]<120&&data.data[k+2]<120;if(fg){min=Math.min(min,yy);max=Math.max(max,yy);maxX=Math.max(maxX,xx);}}let gapPixels=0;if(r.set.hiMD)for(let yy=3;yy<data.height-3;yy++)for(let xx=Math.ceil((r.width-1.5-6.8-.8)*ppm);xx<Math.floor((r.width-1.5-6.8-.2)*ppm);xx++){const k=(yy*data.width+xx)*4,fg=r.set.theme==='dark'?data.data[k]>140&&data.data[k+1]>140&&data.data[k+2]>140:data.data[k]<120&&data.data[k+1]<120&&data.data[k+2]<120;if(fg)gapPixels++;}bands.push({offset:(min+max+1-data.height)/2,maxX,rightPx:right*ppm,gapPixels});}
 // Measure actual downloaded frame bands, independently of production geometry.
 const frontBands=[];for(const r of rects.filter(r=>r.kind==='front'&&r.set.hiMD&&!r.set.hideHeader)){
  const md={x:r.x+38-2-44/11.811,y:r.y+(5-43/11.811)/2,w:44/11.811,h:43/11.811};
  const hi={x:md.x-.5-106/11.811,y:r.y+(5-43/11.811)/2,w:106/11.811,h:43/11.811};
  function measure(q){const column=Math.round((q.x+q.w/2)*ppm),left=Math.floor(q.x*ppm),top=Math.floor(q.y*ppm),bottom=Math.ceil((q.y+q.h)*ppm);let first=Infinity,last=-1,upper=0,lower=0,side=0;
   const darkness=(xx,yy)=>{const k=(yy*c.width+xx)*4;const d=x.getImageData(xx,yy,1,1).data;const bg=r.set.theme==='dark'?[35,31,32]:[255,255,255];return Math.abs(d[0]-bg[0])+Math.abs(d[1]-bg[1])+Math.abs(d[2]-bg[2]);};
   for(let yy=top;yy<bottom;yy++){const d=darkness(column,yy)/765;if(yy<top+4){upper+=d;if(d>.015)first=Math.min(first,yy);}if(yy>=bottom-4){lower+=d;if(d>.015)last=Math.max(last,yy);}}
   const mid=Math.round((q.y+q.h/2)*ppm);for(let xx=left;xx<left+4;xx++)side+=darkness(xx,mid)/765;
   return {center:(first+last+1)/2,upper,lower,side};
  }
  const a=measure(md),b=measure(hi);frontBands.push({md:a,hi:b,centerDelta:b.center-a.center,strokeDelta:Math.max(Math.abs(a.upper-b.upper),Math.abs(a.lower-b.lower),Math.abs(a.side-b.side)),withinMargins:hi.x-r.x>=2&&hi.y-r.y>=0&&md.x+md.w-r.x<=36&&hi.y+hi.h-r.y<=5,gapMm:md.x-(hi.x+hi.w),aspect:272/88});
 }
 return {checks,diffs,parity,bands,frontBands,geometry:m};
 },{b64:b.toString('base64'),kind,project});}
try{
 await page.goto(base+'/studio/');await settle();const initial=await state();check(initial.sets.every(s=>s.hiMD===false),'all defaults unchecked');check(!await page.locator('#hi-md').isChecked(),'checkbox unchecked');check(!requests.some(u=>/hi-md.*png/.test(u)),'unchecked does not request Hi-MD assets');
 const baseProject={schema:'md-studio-project/2',sets:initial.sets,settings:initial.settings,mode:'physical'};
 await load(baseProject);for(const [kind,size] of [['front',[449,638]],['spine',[685,41]],['sheet',[1181,1748]]]){await page.locator('[data-view='+ (kind==='sheet'?'sheet':'label')+']').click();await settle();const b=await dl('export-'+kind,'unchecked-'+kind+'.png',size),a=await audit(b,kind,baseProject);check(a.parity,'unchecked actual preview/download '+kind);for(const c of a.checks)check(c.ok,'unchecked '+c.what);}
 const equality=await page.evaluate(async()=>{const {studio}=await import('./app.mjs'),r=await import('./render.mjs');const s=studio.getState().sets[0],old={...s};delete old.hiMD;const equal=(a,b)=>{const aa=a.getContext('2d').getImageData(0,0,a.width,a.height).data,bb=b.getContext('2d').getImageData(0,0,b.width,b.height).data;return aa.every((v,i)=>v===bb[i]);};return {front:equal((await r.frontCanvas(s)).canvas,(await r.frontCanvas(old)).canvas),spine:equal((await r.spineCanvas(s)).canvas,(await r.spineCanvas(old)).canvas),sheet:equal((await r.sheetCanvas([s,s],{paper:'selphy'})).canvas,(await r.sheetCanvas([old,old],{paper:'selphy'})).canvas)};});check(Object.values(equality).every(Boolean),'missing/unchecked identical front spine sheet pixels');
 const hiddenEqual=await page.evaluate(async()=>{const {studio}=await import('./app.mjs'),r=await import('./render.mjs');const s={...studio.getState().sets[0],hideHeader:true};const a=(await r.frontCanvas({...s,hiMD:true},'physical')).canvas,b=(await r.frontCanvas({...s,hiMD:false},'physical')).canvas;const aa=a.getContext('2d').getImageData(0,0,a.width,a.height).data,bb=b.getContext('2d').getImageData(0,0,b.width,b.height).data;return aa.every((v,i)=>v===bb[i]);});check(hiddenEqual,'hidden header checked/unchecked full front identical');
 for(const setCount of [2,4])for(const theme of ['light','dark'])for(const hidden of [false,true]){
  const p=structuredClone(baseProject);p.settings.setCount=setCount;p.sets.forEach((s,i)=>Object.assign(s,{hiMD:i%2===0,hideHeader:hidden,theme,uppercase:false,album:'Agyp 海岸来信 '.repeat(18),artist:'慢频电台'}));await load(p);check(await page.locator('#hi-md').isChecked(),'checked project reflected in real UI');const prefix=`${setCount}-${theme}-${hidden?'hidden':'header'}`;
  await page.locator('[data-view=label]').click();await settle();const front=await dl('export-front',prefix+'-front.png',[449,638]),spine=await dl('export-spine',prefix+'-spine.png',[685,41]);for(const [kind,b] of [['front',front],['spine',spine]]){const a=await audit(b,kind,p);check(a.parity,'preview/download parity '+prefix+' '+kind);for(const c of a.checks)check(c.ok,c.what+' '+prefix+' '+kind);for(const band of a.bands){check(Math.abs(band.offset)<=1,'spine visible ink remains centered '+JSON.stringify(band));check(band.maxX<band.rightPx&&band.gapPixels===0,'text/mark gap has no foreground pixels');}for(const f of a.frontBands){check(Math.abs(f.centerDelta)<=.5,'download frame vertical centers aligned '+JSON.stringify(f));check(f.strokeDelta<=.25,'download frame thickness matches MiniDisc '+JSON.stringify(f));check(f.withinMargins&&Math.abs(f.gapMm-.5)<1e-8,'physical margins and 0.5mm gap');check(Math.abs(f.aspect-272/88)<1e-8,'official horizontal aspect');}results.push({prefix,kind,...a});}
  if(!hidden&&setCount===4&&theme==='dark'){await writeFile(path.join(out,'sample-front-himd-horizontal.png'),front);await writeFile(path.join(out,'sample-spine-himd.png'),spine);}
  await page.locator('[data-view=sheet]').click();await settle();const sheet=await dl('export-sheet',prefix+'-sheet.png',[1181,1748]),a=await audit(sheet,'sheet',p);await writeFile(path.join(out,'last-sheet-audit.json'),JSON.stringify(a,null,2));check(a.parity,'sheet preview/download parity');for(const c of a.checks)check(c.ok,c.what+' '+prefix+' sheet '+JSON.stringify(a.checks));for(const band of a.bands){check(Math.abs(band.offset)<=1,'sheet spine ink centered');check(band.gapPixels===0,'sheet text/logo gap empty');}check(JSON.stringify(a.geometry)===JSON.stringify((await page.evaluate(async p=>(await import('./geometry.mjs')).sheetManifest(p.sets.slice(0,p.settings.setCount),p.settings),p))),'unchanged manifest');for(const f of a.frontBands){check(Math.abs(f.centerDelta)<=.5,'sheet download frame centers aligned '+JSON.stringify(f));check(f.strokeDelta<=.25,'sheet frame thickness matches '+JSON.stringify(f));check(f.withinMargins&&Math.abs(f.gapMm-.5)<1e-8,'sheet margins and gap');}results.push({prefix,kind:'sheet',...a});
 }
 // Real save/load with independent mixed values, and old v2/v1 files.
 const saved=JSON.parse(await dl('save-project','mixed-project.json'));check(saved.schema==='md-studio-project/2','schema v2 preserved');check(JSON.stringify(saved.sets.map(s=>s.hiMD))==='[true,false,true,false]','mixed flags saved');await page.locator('#hi-md').uncheck();await settle();await load(saved);check(JSON.stringify((await state()).sets)===JSON.stringify(saved.sets),'real mixed roundtrip');for(let i=0;i<4;i++){await page.locator('#set-'+'abcd'[i]).click();await settle();check(await page.locator('#hi-md').isChecked()===saved.sets[i].hiMD,'per-set checkbox restored');}
 const old=structuredClone(baseProject);old.sets.forEach(s=>delete s.hiMD);await load(old);check((await state()).sets.every(s=>s.hiMD===false),'old v2 loads unchecked');old.schema='md-studio-project/1';old.sets=old.sets.slice(0,2);delete old.settings.setCount;await load(old);check((await state()).sets.every(s=>s.hiMD===false),'legacy v1 loads unchecked');
 // All bundled face combinations: independently inspect metrics, gap, truncation and 2mm custom height.
 const metrics=await page.evaluate(async()=>{const {studio}=await import('./app.mjs'),r=await import('./render.mjs');const s=studio.getState().sets[0],out=[];for(const latin of ['atkinson','b612'])for(const cjk of ['noto-sans','noto-serif','wenkai'])for(const sh of [2,3.5]){const cfg={...s,hiMD:true,latin,cjk,sh,uppercase:false,album:'Agyp 海岸来信 '.repeat(40),artist:''};const {info,canvas}=await r.spineCanvas(cfg);const ctx=canvas.getContext('2d');ctx.font=`${Math.min(1.76,sh*.5)}px ${r.fontStack(cfg)}`;const m=ctx.measureText(info.text),center=info.baseline+(m.actualBoundingBoxDescent-m.actualBoundingBoxAscent)/2;out.push({info,center,expected:canvas.height/(300/25.4)/2});}return out;});for(const m of metrics){check(m.info.truncated,'long text shortened');check(m.info.textRight<=m.info.logo.x-1+1e-8,'one mm gap');check(Math.abs(m.center-m.expected)<1e-8,'true glyph ink centered');check(m.info.logo.y>=.2,'logo fits custom height');}
 const compat=structuredClone(baseProject);compat.sets[0].hiMD=true;compat.mode='compat';await load(compat);await page.locator('#set-a').click();await page.locator('[data-view=label]').click();await settle();await dl('export-front','checked-front-compat.png',[448,637]);
 const delayed=await browser.newContext();let release;const gate=new Promise(r=>release=r);await delayed.route('**/assets/branding/hi-md*.png',async r=>{await gate;await r.continue();});const dp=await delayed.newPage();await dp.goto(base+'/studio/');await dp.waitForFunction(()=>!document.querySelector('#export-sheet').disabled);await dp.locator('#hi-md').check();await dp.waitForTimeout(450);check(await dp.locator('#export-front').isDisabled()&&await dp.locator('#export-spine').isDisabled(),'delayed checked marks gate exports');release();await dp.waitForFunction(()=>!document.querySelector('#export-sheet').disabled);check(true,'delayed load recovers');await delayed.close();
 await load(saved);await context.setOffline(true);await dl('export-spine','checked-spine-offline.png',[685,41]);await dl('export-sheet','checked-sheet-offline.png',[1181,1748]);await context.setOffline(false);
 const failed=await browser.newContext();await failed.route('**/assets/branding/hi-md*.png',r=>r.abort());const fp=await failed.newPage();await fp.goto(base+'/studio/');await fp.waitForFunction(()=>!document.querySelector('#export-sheet').disabled);await fp.locator('#hi-md').check();await fp.waitForFunction(()=>document.querySelector('#error').textContent.includes('Hi-MD'));check(await fp.locator('#export-front').isDisabled()&&await fp.locator('#export-spine').isDisabled()&&await fp.locator('#export-sheet').isDisabled(),'missing checked marks gate downloads');await fp.locator('#hide-header').check();await fp.waitForFunction(()=>!document.querySelector('#export-front').disabled);check(await fp.locator('#export-spine').isDisabled(),'hidden front independent but spine bar remains required');await fp.locator('#hi-md').uncheck();await fp.waitForFunction(()=>!document.querySelector('#export-sheet').disabled);check(true,'unchecked removes all Hi-MD resource dependencies');await failed.close();
 check(errors.length===0,'no runtime errors');await writeFile(path.join(out,'test-results.json'),JSON.stringify({status:'PASS',assertions,browser:browser.version(),results,metrics,files,runtimeErrors:errors},null,2));console.log(JSON.stringify({status:'PASS',assertions,configs:8,files:files.length},null,2));
}finally{await context.close();await browser.close();server.close();}
