import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,access} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
import {messages,LANGUAGES,STORAGE_KEY,setLanguage,t,localeError} from '../i18n.mjs';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/i18n'),baseline=path.join(out,'baseline');await mkdir(out,{recursive:true});
let assertions=0;const check=(v,m)=>{assert.ok(v,m);assertions++;},eq=(a,b,m)=>{assert.deepEqual(a,b,m);assertions++;},hash=b=>createHash('sha256').update(b).digest('hex');
const keys=Object.keys(messages.en).sort(),coverage=[],downloads=[],errors=[],requests=[];
for(const lang of LANGUAGES){eq(Object.keys(messages[lang]).sort(),keys,'complete dictionary '+lang);for(const key of keys){const s=messages[lang][key];check(typeof s==='string'&&s.length>0&&!/[\ufffd]|锟斤拷/.test(s),'valid Unicode '+lang+' '+key);eq([...s.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort(),[...messages.en[key].matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort(),'placeholder parity '+lang+' '+key);}}
// Error keys stay live rather than freezing the language at the time of failure.
const bound=localeError('bounded',{nameKey:'frontWidth',min:10,max:85});for(const lang of LANGUAGES){setLanguage(lang,{persist:false});eq(bound.message,t('bounded',{nameKey:'frontWidth',min:10,max:85}),'late-bound dimension name');}setLanguage('en',{persist:false});
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright-core');
let hasBaseline=await access(path.join(baseline,'index.html')).then(()=>true,()=>false);
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),isOld=u.pathname.startsWith('/baseline/'),dir=isOld?baseline:root;let rel=u.pathname.replace(/^\/(studio|baseline)\//,'/');if(rel.endsWith('/'))rel+='index.html';const file=path.resolve(dir,'.'+rel);if(!file.startsWith(dir+path.sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.woff2':'font/woff2','.json':'application/json'})[path.extname(file)]||'text/plain');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1100}}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await context.route('**/*',r=>r.request().url().startsWith(base)||r.request().url().startsWith('blob:'+base)||r.request().url().startsWith('data:')?r.continue():r.abort());
async function settle(p=page){await p.waitForTimeout(180);await p.waitForFunction(()=>!document.querySelector('#export-front').disabled&&!document.querySelector('#export-sheet').disabled&&!document.querySelector('#export-spine').disabled,null,{timeout:60000});}
async function state(p=page){return p.evaluate(async()=> (await import('./app.mjs')).studio.getState());}
async function projectLoad(p,project){await p.locator('#load-project').setInputFiles({name:'i18n-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await settle(p);}
async function dl(p,id,name){const waiting=p.waitForEvent('download');await p.locator('#'+id).click();const d=await waiting;await d.saveAs(path.join(out,name));const data=await readFile(path.join(out,name));downloads.push({path:name,downloadName:d.suggestedFilename(),bytes:data.length,sha256:hash(data)});await settle(p);return hash(data);}
async function choose(lang,p=page){await p.locator('#language').selectOption(lang);eq(await p.locator('html').getAttribute('lang'),lang,'html language '+lang);eq(await p.evaluate(k=>localStorage.getItem(k),STORAGE_KEY),lang,'stored language '+lang);}
async function bindingsCheck(lang){const instructions=await page.locator('.instructions li').allTextContents();eq(instructions,[messages[lang].instruction1+messages[lang].uncorrected+messages[lang].instruction1End,messages[lang].instruction2,messages[lang].instruction3,messages[lang].instruction4+messages[lang].cannot+messages[lang].instruction4End],'complete instructions '+lang);const result=await page.evaluate(async()=>{const i=await import('./i18n.mjs'),b=i.uiBindings();return {texts:b.texts.map(v=>({key:v.key,actual:v.node.nodeValue,expected:v.before+i.t(v.key)+v.after})),attrs:b.attributes.filter(v=>v.node.id!=='preview').map(v=>({key:v.key,actual:v.node.getAttribute(v.attr),expected:i.t(v.key)}))};});for(const b of [...result.texts,...result.attrs])eq(b.actual,b.expected,'rendered binding '+lang+' '+b.key);check(result.texts.length>85,'static text coverage');eq(result.attrs.map(v=>v.key).sort(),['metaDescription','home','language','language','editorAria','setAria','uploadAria','previewAria','previewMode','spinePreview','loadAria','print'].sort(),'complete static aria/title/meta inventory');return {texts:result.texts.length,attributes:result.attrs.length};}
const expected={en:{album:'Album title',save:'Save project',font:'CJK font',paper:'Unknown paper preset',timeout:'Font loading timed out'},'zh-Hans':{album:'专辑名称',save:'保存项目',font:'中文字体',paper:'未知纸张',timeout:'字体载入超时'},'zh-Hant':{album:'專輯名稱',save:'儲存專案',font:'中文字型',paper:'未知紙張',timeout:'字型載入逾時'},es:{album:'Título del álbum',save:'Guardar proyecto',font:'Fuente CJK',paper:'Formato de papel desconocido',timeout:'Se agotó el tiempo de carga de la fuente'},fr:{album:'Titre de l’album',save:'Enregistrer le projet',font:'Police CJK',paper:'Format de papier inconnu',timeout:'Délai de chargement de la police dépassé'},ja:{album:'アルバム名',save:'プロジェクトを保存',font:'CJK フォント',paper:'用紙のプリセットが不明です',timeout:'フォントの読み込みがタイムアウトしました'}};
try{
 await page.goto(base+'/studio/');await settle();
 const inventory=await page.evaluate(({html,known})=>{const doc=new DOMParser().parseFromString(html,'text/html'),walker=doc.createTreeWalker(doc.documentElement,4),raw=[];for(let node=walker.nextNode();node;node=walker.nextNode())if(!node.parentElement.closest('script,style,#language')&&node.nodeValue.trim())raw.push(node.nodeValue.trim());const attrs=[];for(const n of doc.querySelectorAll('[aria-label],[title],[placeholder],meta[name=description]'))for(const a of ['aria-label','title','placeholder','content'])if(n.hasAttribute(a))attrs.push(n.getAttribute(a));const invariant=['A','B','C','D','01','02','03','04','38 × 54','mm','B612','Hi-MD','PNG · 300 DPI','·'];return {unmapped:raw.filter(s=>!known.includes(s)&&!invariant.includes(s)),unmappedAttrs:attrs.filter(s=>!known.includes(s)),texts:raw.length,attributes:attrs.length};},{html:await readFile(path.join(root,'index.html'),'utf8'),known:Object.values(messages.en).map(s=>s.trim())});eq(inventory.unmapped,[],'all static UI text is keyed or a documented brand/metric/tab invariant');eq(inventory.unmappedAttrs,[],'all static accessibility/meta text is keyed');
 eq(await page.locator('html').getAttribute('lang'),'en','absent storage defaults English');eq(await page.locator('#language').inputValue(),'en','selector defaults English');eq(await page.evaluate(k=>localStorage.getItem(k),STORAGE_KEY),null,'absent storage remains absent');
 eq(await page.locator('#language option').allTextContents(),['English','简体中文','繁體中文','Español','Français','日本語'],'language order and native names');eq(await page.locator('#language option').evaluateAll(nodes=>nodes.map(n=>n.value)),LANGUAGES,'language value order');
 const initial=await state(),project={schema:'md-studio-project/2',sets:initial.sets,settings:initial.settings,mode:'physical'};project.sets.forEach((s,i)=>Object.assign(s,{album:'海岸の音 / Été — Canción '+i,artist:'Mira / 慢频電台',uppercase:false,hiMD:i%2===0}));await projectLoad(page,project);
 const stateBefore=await state(),canvasBefore=await page.locator('#preview').evaluate(c=>c.toDataURL());
 for(const lang of LANGUAGES){await choose(lang);const n=await bindingsCheck(lang);check((await page.locator('label').filter({has:page.locator('#album')}).textContent()).includes(expected[lang].album),'independent album translation '+lang);eq(await page.locator('#save-project').textContent(),expected[lang].save,'independent save translation '+lang);check((await page.locator('label').filter({has:page.locator('#cjk')}).textContent()).includes(expected[lang].font),'independent CJK translation '+lang);
  eq(await page.locator('#export-sheet').textContent(),messages[lang].sheetDownload.replace('{count}','4').replace('{pixels}','1181 × 1748'),'dynamic sheet button '+lang);eq(await page.locator('#preview').getAttribute('aria-label'),messages[lang].labelCaption.replace('{set}','A'),'dynamic preview aria '+lang);eq(await page.locator('#profile-note').textContent(),messages[lang].profileOriginal,'dynamic profile note '+lang);eq(await page.locator('#art-info').textContent(),messages[lang].sampleCover,'dynamic cover note '+lang);check((await page.locator('#render-status').textContent()).includes(messages[lang].ready),'dynamic ready status '+lang);eq(await state(),stateBefore,'UI language never modifies project state '+lang);eq(await page.locator('#preview').evaluate(c=>c.toDataURL()),canvasBefore,'UI language never repaints preview '+lang);eq(await page.locator('#album').inputValue(),project.sets[0].album,'typed content unchanged '+lang);
  const geometryErrors=await page.evaluate(async()=>{const g=await import('./geometry.mjs'),r=await import('./render.mjs'),i=await import('./i18n.mjs');const capture=fn=>{try{fn();return null;}catch(e){return e.message;}};return [capture(()=>g.sheetManifest([{profile:'original',sw:58,sh:3.5},{profile:'original',sw:58,sh:3.5}],{paper:'unknown'})),capture(()=>r.calibrationCanvas({paper:'unknown'})),i.localeError('fontTimeout').message,capture(()=>g.dimensions({profile:'custom',w:0,h:54,sw:58,sh:3.5}))];});eq(geometryErrors[0],expected[lang].paper,'actual geometry error '+lang);eq(geometryErrors[1],expected[lang].paper,'actual calibration error '+lang);eq(geometryErrors[2],expected[lang].timeout,'timeout translation '+lang);check(geometryErrors[3].includes(messages[lang].frontWidth),'localized bounded parameter '+lang);
  // All static/error translations actually pass through real DOM text nodes; no HTML injection.
  const fixture=await page.evaluate(async()=>{const i=await import('./i18n.mjs'),host=document.createElement('div');host.id='locale-glyph-fixture';host.style.cssText='background:white;color:black;font:18px system-ui;padding:12px;position:relative;z-index:9';host.textContent=[i.t('album'),i.t('save'),i.t('fontTimeout'),i.t('animated')].join('\n');document.body.append(host);return {text:host.textContent,width:host.getBoundingClientRect().width,height:host.getBoundingClientRect().height,ready:document.fonts.status};});check(fixture.width>0&&fixture.height>20&&fixture.ready==='loaded','CJK/accent fixture laid out '+lang);check(!fixture.text.includes('\ufffd'),'no replacement glyph '+lang);await page.locator('#locale-glyph-fixture').screenshot({path:path.join(out,'glyphs-'+lang+'.png')});await page.locator('#locale-glyph-fixture').evaluate(n=>n.remove());
  await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(120);await page.screenshot({path:path.join(out,'ui-'+lang+'.png'),fullPage:true});
  const hashes={};for(const kind of ['front','spine','sheet','calibration']){hashes[kind]=await dl(page,'export-'+kind,lang+'-'+kind+'.png');const key=({front:'fileFront',spine:'fileSpine',sheet:'fileSheet',calibration:'fileCalibration'})[kind];const part=messages[lang][key].replace('{count}','4').replace('{paper}','SELPHY');check(downloads.at(-1).downloadName.includes(part),'localized download filename '+lang+' '+kind);}hashes.manifest=await dl(page,'export-manifest',lang+'-geometry.json');hashes.project=await dl(page,'save-project',lang+'-project.json');
  await page.locator('#export-mode').selectOption('compat');await settle();hashes.compat=await dl(page,'export-front',lang+'-front-compat.png');await page.locator('#export-mode').selectOption('physical');await settle();
  if(coverage.length)eq(hashes,coverage[0].hashes,'actual downloaded bytes stable across all locales '+lang);coverage.push({language:lang,keys:keys.length,bindings:n,hashes,glyphFixture:fixture});
 }
 // Second configuration: two sets, light theme, hidden headers, measured correction, 4×6 paper.
 const second=structuredClone(project);second.settings={...second.settings,setCount:2,paper:'inch',calibrated:true,measuredX:52,measuredY:51};second.sets.forEach(s=>Object.assign(s,{theme:'light',hideHeader:true,latin:'b612',cjk:'wenkai'}));await projectLoad(page,second);const matrix=[];for(const lang of LANGUAGES){await choose(lang);const hashes={};for(const kind of ['front','spine','sheet','calibration'])hashes[kind]=await dl(page,'export-'+kind,'two-light-'+lang+'-'+kind+'.png');if(matrix.length)eq(hashes,matrix[0].hashes,'two-set alternate configuration byte parity '+lang);matrix.push({lang,hashes});}
 // If the frozen pre-feature tree is available, compare to 2b4e4ff actual button downloads too.
 const baselineProof=[];if(hasBaseline){const old=await context.newPage();await old.goto(base+'/baseline/');await settle(old);for(const [name,p,reference] of [['four-dark',project,coverage[0].hashes],['two-light',second,matrix[0].hashes]]){await projectLoad(old,p);const hashes={};for(const kind of ['front','spine','sheet','calibration']){hashes[kind]=await dl(old,'export-'+kind,'baseline-'+name+'-'+kind+'.png');eq(hashes[kind],reference[kind],'unchanged baseline bytes '+name+' '+kind);}if(reference.compat){await old.locator('#export-mode').selectOption('compat');await settle(old);hashes.compat=await dl(old,'export-front','baseline-'+name+'-front-compat.png');eq(hashes.compat,reference.compat,'unchanged baseline compatibility bytes');}baselineProof.push({name,hashes});}await old.close();}
 // Restore initial UI content for screenshots/reload tests and check errors via real controls.
 await projectLoad(page,project);
 for(const lang of LANGUAGES){await choose(lang);await page.reload();await settle();eq(await page.locator('#language').inputValue(),lang,'selection restored on reload '+lang);eq(await page.locator('html').getAttribute('lang'),lang,'html restored on reload '+lang);eq(await page.locator('#save-project').textContent(),expected[lang].save,'translated immediately after reload '+lang);
  await page.locator('#load-project').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await page.waitForFunction(()=>!document.querySelector('#error').hidden);eq(await page.locator('#error').textContent(),messages[lang].invalidJson,'real JSON error '+lang);
  await page.locator('#art-file').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await page.waitForFunction(()=>!document.querySelector('#error').hidden);eq(await page.locator('#error').textContent(),messages[lang].imageContainer,'real cover error '+lang);
  await page.locator('#album').fill('😀');await page.waitForFunction(()=>document.querySelector('#export-front').disabled&&document.querySelector('#error').textContent.includes('😀'));check((await page.locator('#error').textContent()).includes(messages[lang].missingGlyph.replace('{chars}','😀')),'real glyph error '+lang);await page.locator('#album').fill('海岸の音 / Été — Canción');await settle();
 }
 // An already-visible upload error must translate instantly, not disappear on language change.
 await choose('en');await page.locator('#art-file').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('bad')});await page.waitForFunction(()=>!document.querySelector('#error').hidden);await choose('ja');eq(await page.locator('#error').textContent(),messages.ja.imageContainer,'existing error switches language');
 await context.setOffline(true);await choose('fr');eq(await page.locator('#save-project').textContent(),expected.fr.save,'offline UI switching');await dl(page,'export-spine','offline-fr-spine.png');await context.setOffline(false);
 // Unsupported storage value and storage exceptions must safely default to English.
 await page.evaluate(k=>localStorage.setItem(k,'unsupported'),STORAGE_KEY);await page.reload();await settle();eq(await page.locator('html').getAttribute('lang'),'en','unsupported stored value defaults English');await page.evaluate(k=>localStorage.removeItem(k),STORAGE_KEY);await page.reload();await settle();eq(await page.locator('html').getAttribute('lang'),'en','cleared storage defaults English');
 for (const denial of ['getter','methods']) {
 const restricted=await browser.newContext();await restricted.addInitScript(kind=>{if(kind==='getter')Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}});else {Storage.prototype.getItem=()=>{throw new DOMException('blocked','SecurityError');};Storage.prototype.setItem=()=>{throw new DOMException('blocked','SecurityError');};}},denial);
 const rp=await restricted.newPage(),restrictedErrors=[];rp.on('pageerror',e=>restrictedErrors.push(e.message));await rp.goto(base+'/studio/');await settle(rp);eq(await rp.locator('html').getAttribute('lang'),'en','blocked storage default '+denial);
 for(const lang of LANGUAGES){await rp.locator('#language').selectOption(lang);eq(await rp.locator('#save-project').textContent(),expected[lang].save,'blocked static '+denial+lang);eq(await rp.locator('#export-sheet').textContent(),messages[lang].sheetDownload.replace('{count}','4').replace('{pixels}','1181 × 1748'),'blocked dynamic sheet '+denial+lang);eq(await rp.locator('#profile-note').textContent(),messages[lang].profileOriginal,'blocked dynamic profile '+denial+lang);eq(await rp.locator('#language').inputValue(),lang,'session language '+denial+lang);}
 eq(restrictedErrors,[],'no uncaught storage error '+denial);await rp.reload();await settle(rp);eq(await rp.locator('html').getAttribute('lang'),'en','blocked storage reload default '+denial);await restricted.close();
 }
 // Real font load timeout, no 20-second wall-clock wait: advance only the font timeout timer.
 const timed=await browser.newContext();await timed.addInitScript(()=>{const real=window.setTimeout;window.setTimeout=(fn,ms,...args)=>real(fn,ms===20000?25:ms,...args);});await timed.route('**/*.woff2',async r=>{await new Promise(resolve=>setTimeout(resolve,250));await r.continue().catch(()=>{});});const tp=await timed.newPage();await tp.goto(base+'/studio/');await tp.waitForFunction(()=>document.querySelector('#font-status').textContent.includes('Font loading timed out'));for(const lang of LANGUAGES){await tp.locator('#language').selectOption(lang);check((await tp.locator('#font-status').textContent()).includes(expected[lang].timeout),'actual FontFace timeout DOM '+lang);check(await tp.locator('#export-front').isDisabled(),'timed fonts block export '+lang);}await timed.close();
 // Responsive top-right control and no horizontal overflow in every language.
 await page.setViewportSize({width:390,height:844});for(const lang of LANGUAGES){await choose(lang);check(await page.locator('#language').isVisible(),'mobile language selector '+lang);const fit=await page.evaluate(()=>({body:document.documentElement.scrollWidth,width:innerWidth,selector:document.querySelector('#language').getBoundingClientRect().toJSON()}));check(fit.body<=fit.width+1,'mobile no overflow '+lang+' '+JSON.stringify(fit));check(fit.selector.right<=fit.width&&fit.selector.top<160,'mobile selector at page top-right '+lang);}await page.screenshot({path:path.join(out,'ui-ja-mobile.png'),fullPage:true});
 check(errors.length===0,'no uncaught browser errors');check(requests.every(u=>u.startsWith(base)||u.startsWith('data:')||u.startsWith('blob:'+base)),'no external or translation requests');
 await writeFile(path.join(out,'test-results.json'),JSON.stringify({status:'PASS',assertions,browser:browser.version(),keyCount:keys.length,staticInventory:inventory,coverage,matrix,baselineAvailable:hasBaseline,baselineCommit:hasBaseline?'2b4e4ffd015386401385145900a3d958a5cc14fc':null,baselineProof,downloads,runtimeErrors:errors,requests},null,2)+'\n');console.log(JSON.stringify({status:'PASS',assertions,keys:keys.length,languages:LANGUAGES,downloads:downloads.length,baselineCompared:hasBaseline}));
}finally{await context.close();await browser.close();await new Promise(r=>server.close(r));}
