import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/logo-site-fix');await mkdir(out,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'/Users/xzhou/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core');
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname.replace(/^\/studio\//,'/');if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.png':'image/png','.json':'application/json','.css':'text/css','.woff2':'font/woff2'})[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:1000}});await context.route('**/*',r=>r.request().url().startsWith(base)||r.request().url().startsWith('blob:'+base)?r.continue():r.abort());const page=await context.newPage();let assertions=0;const check=(v,m)=>{assert.ok(v,m);assertions++;};const results=[];
async function settle(){await page.waitForTimeout(180);await page.waitForFunction(()=>!document.querySelector('#export-front').disabled);}
async function download(id,name){const wait=page.waitForEvent('download');await page.locator('#'+id).click();const d=await wait;await d.saveAs(path.join(out,name));await settle();return (await readFile(path.join(out,name))).toString('base64');}
async function pixels(png,theme,sheet=false,hidden=false){return page.evaluate(async({png,theme,sheet,hidden})=>{const img=new Image();img.src='data:image/png;base64,'+png;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);const logo=new Image();logo.src=new URL('./assets/branding/minidisc.png',location.href);await logo.decode();const expected=document.createElement('canvas');expected.width=img.width;expected.height=img.height;const ex=expected.getContext('2d');const ppm=300/25.4, lw=44/11.811,lh=43/11.811;let origins=[{x:0,y:0}];if(sheet){const {studio}=await import('./app.mjs');const {sheetManifest}=await import('./geometry.mjs');const st=studio.getState();origins=sheetManifest(st.sets.slice(0,st.settings.setCount),st.settings).sets.map(s=>s.labels.find(l=>l.kind==='front').renderedMm);}
const diffs=[];for(const o of origins){ex.save();ex.scale(ppm,ppm);ex.translate(o.x,o.y);ex.fillStyle=theme==='dark'?'#231F20':'white';ex.fillRect(30,0,8,5);if(!hidden)ex.drawImage(logo,36-lw,(5-lh)/2,lw,lh);ex.restore();const x=Math.floor((o.x+36-lw)*ppm),y=Math.floor((o.y+(5-lh)/2)*ppm),w=46,h=45,a=ctx.getImageData(x,y,w,h).data,b=ex.getImageData(x,y,w,h).data;let n=0,max=0;for(let i=0;i<a.length;i++){if(a[i]!==b[i])n++;max=Math.max(max,Math.abs(a[i]-b[i]));}diffs.push({differentChannels:n,maxDelta:max});}const preview=document.querySelector('#preview');const pc=preview.getContext('2d');let previewEqual=preview.width===canvas.width&&preview.height===canvas.height;if(previewEqual){const a=pc.getImageData(0,0,canvas.width,canvas.height).data,b=ctx.getImageData(0,0,canvas.width,canvas.height).data;previewEqual=a.every((v,i)=>v===b[i]);}return {width:img.width,height:img.height,diffs,previewEqual};},{png,theme,sheet,hidden});}
try{await page.goto(base+'/studio/');await settle();await page.locator('#set-count').selectOption('2');await settle();await page.locator('#export-mode').selectOption('physical');await settle();for(const theme of ['dark','light']){await page.locator(`[name=theme][value=${theme}]`).check();await settle();const png=await download('export-front',`front-${theme}.png`),r=await pixels(png,theme);check(r.width===449&&r.height===638,'physical size');check(r.diffs.every(d=>d.differentChannels===0),'logo crop equals independent geometry '+theme);check(r.previewEqual,'preview matches real download '+theme);results.push({theme,...r});await page.screenshot({path:path.join(out,`preview-${theme}.png`),fullPage:true});}
// No art makes the header-hidden region independently testable (cover otherwise occupies it).
const state=await page.evaluate(async()=>{const {studio}=await import('./app.mjs');const s=studio.getState();return {schema:'md-label-studio/1',...s};});
await page.locator('#hide-header').check();await settle();const hidden=await download('export-front','front-hidden.png');const hiddenCheck=await page.evaluate(async()=>{const {studio}=await import('./app.mjs');const {frontCanvas}=await import('./render.mjs');const s={...studio.getState().sets[0],art:{type:'none'},hideHeader:true};const c=(await frontCanvas(s,'physical')).canvas,d=c.getContext('2d').getImageData(382,8,42,43).data;return d.every(v=>v===255);});check(hiddenCheck,'hidden header has no logo');
await page.locator('#hide-header').uncheck();await page.locator('#set-b').click();await page.locator('[name=theme][value=light]').check();await settle();await page.locator('[data-view=sheet]').click();await settle();const sheet=await download('export-sheet','sheet-two-sets.png'),sr=await pixels(sheet,'light',true);check(sr.width===1181&&sr.height===1748,'sheet size');check(sr.diffs.length===2&&sr.diffs.every(d=>d.differentChannels===0),'both sheet logo crops');check(sr.previewEqual,'sheet preview exact download');results.push({sheet:true,...sr});await page.screenshot({path:path.join(out,'preview-sheet.png'),fullPage:true});await context.setOffline(true);await download('export-sheet','sheet-offline.png');check((await readFile(path.join(out,'sheet-offline.png'))).equals(await readFile(path.join(out,'sheet-two-sets.png'))),'offline exact export');await context.setOffline(false);
const failed=await browser.newContext();await failed.route('**/assets/branding/minidisc.png',r=>r.abort());const fp=await failed.newPage();await fp.goto(base+'/studio/');await fp.locator('#set-count').selectOption('2');await fp.waitForFunction(()=>document.querySelector('#error').textContent.includes('MiniDisc'));check(await fp.locator('#export-front').isDisabled(),'missing logo blocks front');check(await fp.locator('#export-sheet').isDisabled(),'missing logo blocks sheet');check(!await fp.locator('#export-spine').isDisabled(),'spine remains independent');await fp.locator('#hide-header').check();await fp.waitForFunction(()=>!document.querySelector('#export-front').disabled);check(await fp.locator('#export-sheet').isDisabled(),'other visible header still blocks sheet');await fp.locator('#set-b').click();await fp.locator('#hide-header').check();await fp.waitForFunction(()=>!document.querySelector('#export-sheet').disabled);check(true,'both hidden remove logo dependency');await fp.screenshot({path:path.join(out,'missing-logo-hidden.png'),fullPage:true});await failed.close();
const delayed=await browser.newContext();let release;const gate=new Promise(r=>release=r);await delayed.route('**/assets/branding/minidisc.png',async r=>{await gate;await r.continue();});const dp=await delayed.newPage();await dp.goto(base+'/studio/');await dp.waitForTimeout(700);check(await dp.locator('#export-front').isDisabled(),'delayed logo gates export');release();await dp.waitForFunction(()=>!document.querySelector('#export-front').disabled);check(true,'delayed load recovers');await delayed.close();
await writeFile(path.join(out,'logo-tests.json'),JSON.stringify({status:'PASS',assertions,browser:browser.version(),results},null,2));console.log(JSON.stringify({status:'PASS',assertions,results},null,2));}finally{await browser.close();server.close();}
