import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.resolve(root,'../artifacts/four-set'),observe=process.argv.includes('--observe-old');await mkdir(out,{recursive:true});
const {chromium}=createRequire(import.meta.url)('/Users/xzhou/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core');
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://localhost').pathname;if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.mjs':'text/javascript','.html':'text/html','.woff2':'font/woff2','.css':'text/css','.png':'image/png'})[path.extname(f)]||'text/plain');res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),errors=[],results=[],files=[];let assertions=0;page.on('pageerror',e=>errors.push(e.message));const check=(v,m)=>{assert.ok(v,m);assertions++;};
async function settle(){await page.waitForTimeout(250);await page.waitForFunction(()=>!document.querySelector('#export-spine').disabled&&!document.querySelector('#export-sheet').disabled,{},{timeout:60000});}
async function dl(id,name){const wait=page.waitForEvent('download',{timeout:60000});await page.locator('#'+id).click();const d=await wait;await d.saveAs(path.join(out,name));const b=await readFile(path.join(out,name));files.push({path:name,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')});await settle();return b;}
async function bands(png,rects,theme){return page.evaluate(async({b64,rects,theme})=>{const i=new Image();i.src='data:image/png;base64,'+b64;await i.decode();const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const x=c.getContext('2d');x.drawImage(i,0,0);return rects.map(r=>{const d=x.getImageData(r.x,r.y,r.width,r.height).data;let min=Infinity,max=-1,pixels=0;for(let yy=2;yy<r.height-2;yy++)for(let xx=8;xx<r.width-8;xx++){const k=(yy*r.width+xx)*4,fg=theme==='dark'?d[k]>140&&d[k+1]>140&&d[k+2]>140:d[k]<120&&d[k+1]<120&&d[k+2]<120;if(fg){min=Math.min(min,yy);max=Math.max(max,yy);pixels++;}}return {min,max,pixels,topGap:min,bottomGap:r.height-1-max,textCenter:(min+max+1)/2,labelCenter:r.height/2,offsetPx:(min+max+1-r.height)/2,rect:r};});},{b64:png.toString('base64'),rects,theme});}
try{
 await page.goto(base+'/dist/');await settle();const initial=await page.evaluate(async()=> (await import('./app.mjs')).studio.getState());
 const configs=[];for(const latin of (observe?['atkinson']:['atkinson','b612']))for(const cjk of (observe?['noto-sans']:['noto-sans','noto-serif','wenkai']))for(const [kind,text] of [['latin','Agyp QÉ 2026'],['cjk','海岸来信慢频电台'],['mixed','Agyp 海岸来信 2026']])for(const theme of ['dark','light'])configs.push({latin,cjk,kind,text,theme,setCount:4});
 if(!observe)for(const theme of ['dark','light'])configs.push({latin:'atkinson',cjk:'noto-sans',kind:'long',text:'Agyp 海岸来信 '.repeat(60),theme,setCount:2});
 for(let n=0;n<configs.length;n++){
  const cfg=configs[n],project={schema:'md-studio-project/2',sets:structuredClone(initial.sets),settings:{...initial.settings,setCount:cfg.setCount},mode:'physical'};for(const s of project.sets)Object.assign(s,{album:cfg.text,artist:'',year:'',uppercase:false,latin:cfg.latin,cjk:cfg.cjk,theme:cfg.theme});await page.locator('#load-project').setInputFiles({name:'spine-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await settle();
  const prefix=(observe?'spine-before-':'spine-after-')+String(n).padStart(2,'0'),standalone=await dl('export-spine',prefix+'.png');check(standalone.readUInt32BE(16)===685&&standalone.readUInt32BE(20)===41,'standalone 685x41');const one=await bands(standalone,[{x:0,y:0,width:685,height:41}],cfg.theme);
  const manifest=JSON.parse(await dl('export-manifest',prefix+'-geometry.json'));const sheet=await dl('export-sheet',prefix+'-sheet.png');check(sheet.readUInt32BE(16)===1181&&sheet.readUInt32BE(20)===1748,'sheet unchanged 1181x1748');const rects=manifest.sets.map(s=>s.labels.find(l=>l.kind==='spine').rectPx),many=await bands(sheet,rects,cfg.theme);
  for(const band of [...one,...many]){check(band.pixels>50,'text band nonempty');if(!observe){check(Math.abs(band.offsetPx)<=1,'visible spine text band centered within 1 raster pixel: '+JSON.stringify({cfg,band}));check(band.topGap>=5&&band.bottomGap>=5,'text safely clear of border');}}
  results.push({config:cfg,standalone:one[0],sheet:many});
  if(!observe&&cfg.latin==='atkinson'&&cfg.cjk==='noto-sans'&&cfg.kind==='mixed')await writeFile(path.join(out,'spine-centered-'+cfg.theme+'.png'),standalone);
 }
 check(errors.length===0,'no runtime page errors');const report={status:observe?'OBSERVED_OLD':'PASS',assertions,browser:browser.version(),threshold:'Visible ink band midpoint within 1 raster pixel of physical label center; border excluded; foreground threshold specified in independent test',results,files,runtimeErrors:errors};await writeFile(path.join(out,observe?'spine-before-results.json':'spine-test-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,assertions,configs:configs.length,maxAbsOffset:Math.max(...results.flatMap(r=>[r.standalone,...r.sheet].map(b=>Math.abs(b.offsetPx))))},null,2));
}finally{await context.close();await browser.close();server.close();}
