import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {DPI,PPM,px,dimensions,calibration,sheetManifest,frontRaster,safeFilename,overlaps} from '../geometry.mjs';
import {crc32,setPngDpi} from '../png.mjs';
let checks=0;const ok=(v)=>{assert.ok(v);checks++;};const eq=(a,b)=>{assert.deepEqual(a,b);checks++;};const fails=f=>{assert.throws(f);checks++;};
const s={profile:'original',sw:58,sh:3.5},cfg={paper:'selphy',calibrated:false,measuredX:50,measuredY:50};
eq(frontRaster(s,'compat'),{width:448,height:637,scale:11.811,compat:true});eq(frontRaster(s,'physical').width,449);eq(frontRaster(s,'physical').height,638);eq(px(100),1181);eq(px(148),1748);eq(px(101.6),1200);eq(px(152.4),1800);eq(dimensions({...s,profile:'vendor'}).w,32);eq(dimensions({...s,profile:'sony'}).h,52.75);fails(()=>frontRaster({...s,profile:'vendor'},'compat'));fails(()=>dimensions({...s,profile:'custom',w:0,h:54}));fails(()=>dimensions({...s,sh:NaN}));
const defaults=sheetManifest([s,s],cfg);eq(defaults.exportPx,{width:1181,height:1748});eq(defaults.sets.length,2);eq(defaults.calibration.mode,'none');eq(defaults.calibration.x.factor,1);eq(sheetManifest([s,s],{...cfg,paper:'inch'}).exportPx,{width:1200,height:1800});
const measured=sheetManifest([s,s],{...cfg,calibrated:true,measuredX:52,measuredY:51});eq(measured.calibration.x.factor,50/52);eq(measured.calibration.y.factor,50/51);eq(measured.exportPx,defaults.exportPx);for(const [i,set] of measured.sets.entries())for(const [j,l]of set.labels.entries()){const r=l.renderedMm,d=l.designMm;ok(Math.abs(r.x-(50+(d.x-50)*50/52))<1e-9);ok(Math.abs(r.y-(74+(d.y-74)*50/51))<1e-9);ok(l.cutline.placement==='inside');ok(Math.abs(l.cutline.widthPx.x-.1*PPM*50/52)<1e-9);}
fails(()=>sheetManifest([s,s],{...cfg,calibrated:true,measuredX:35,measuredY:35}));fails(()=>sheetManifest([{...s,profile:'custom',w:80,h:110},s],cfg));fails(()=>calibration({...cfg,calibrated:true,measuredX:0}));ok(!overlaps({x:0,y:0,width:2,height:2},{x:2,y:0,width:2,height:2}));ok(overlaps({x:0,y:0,width:2,height:2},{x:1,y:0,width:2,height:2}));eq(safeFilename('a/b:c?d*'), 'a_b_c_d_');eq(safeFilename(''), '未命名专辑');eq(safeFilename('CON'),'_CON');eq(safeFilename('海岸来信'),'海岸来信');
const tiny=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');const png=setPngDpi(tiny);let densityCount=0;for(let at=8;at<png.length;){const v=new DataView(png.buffer),len=v.getUint32(at),type=new TextDecoder().decode(png.subarray(at+4,at+8));if(type==='pHYs'){densityCount++;eq(v.getUint32(at+8),11811);eq(v.getUint32(at+12),11811);eq(png[at+16],1);eq(v.getUint32(at+8+len),crc32(png.subarray(at+4,at+8+len)));}at+=12+len;}eq(densityCount,1);eq(setPngDpi(png).length,png.length);fails(()=>setPngDpi(new Uint8Array(33)));
const fonts=JSON.parse(readFileSync(new URL('../assets/fonts/manifest.json',import.meta.url)));let total=0;for(const [k,f]of Object.entries(fonts)){const bytes=readFileSync(new URL('../assets/fonts/'+f.file,import.meta.url));eq(bytes.length,f.bytes);eq(createHash('sha256').update(bytes).digest('hex'),f.sha256);ok(f.bytes<25*1024*1024);ok(readFileSync(new URL('../assets/fonts/'+f.licenseFile,import.meta.url),'utf8').includes('SIL OPEN FONT LICENSE'));total+=f.bytes;}ok(total<25*1024*1024);
try{const {validateManifest}=await import('../../tests/geometry-check.mjs');for(const m of [defaults,measured,sheetManifest([s,s],{...cfg,paper:'inch'})]){const result=validateManifest(m);assert.ok(result.ok,JSON.stringify(result.errors));checks++;}console.log('Independent sibling geometry validator: 3 production manifests PASS');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')console.log('Sibling independent validator absent (portable distribution); local assertions used.');else throw e;}
console.log(`${checks} unit assertions passed; fonts ${(total/1024/1024).toFixed(2)} MiB; DPI ${DPI}.`);

const four=sheetManifest([s,s,s,s],cfg);eq(four.sets.map(s=>s.id),['A','B','C','D']);eq(four.exportPx,{width:1181,height:1748});
for(let i=0;i<4;i++){eq(four.sets[i].labels[0].designMm,{x:i%2?53:9,y:i<2?6:62,width:38,height:54});eq(four.sets[i].labels[1].designMm,{x:21,y:118+i*5.5,width:58,height:3.5});}
for(const bad of [{w:45,h:54},{w:38,h:57},{w:70,h:80}])fails(()=>sheetManifest([{...s,profile:'custom',...bad},s,s,s],cfg));
fails(()=>sheetManifest([s,s,s,{...s,sh:10}],cfg));fails(()=>sheetManifest([s,s,s,{...s,sw:85}],cfg));fails(()=>sheetManifest([s,s,s],cfg));
eq(sheetManifest([s,s,s,s],{...cfg,paper:'inch'}).exportPx,{width:1200,height:1800});
console.log(`${checks} total assertions including four-set anchors/collision rejection passed.`);
